-- Seed the 50 Laws of Life into the laws table
INSERT INTO public.laws (law_number, title) VALUES
(1, 'Your character is your currency'),
(2, 'Wisdom precedes wealth'),
(3, 'Faith is the foundation of everything'),
(4, 'Leadership is service'),
(5, 'Excellence is a daily choice'),
(6, 'Your network determines your net worth'),
(7, 'Education is the greatest investment'),
(8, 'Legacy matters more than luxury'),
(9, 'Discipline creates freedom'),
(10, 'Your word is your bond'),
(11, 'Give more than you take'),
(12, 'Vision requires patience'),
(13, 'Failure is a teacher, not a finality'),
(14, 'Integrity cannot be compromised'),
(15, 'Purpose precedes profit'),
(16, 'Your mentors shape your destiny'),
(17, 'Time is more valuable than money'),
(18, 'Generosity creates abundance'),
(19, 'Knowledge without action is empty'),
(20, 'Your environment shapes your reality'),
(21, 'Humility attracts greatness'),
(22, 'Relationships are sacred trusts'),
(23, 'Consistency beats intensity'),
(24, 'Your legacy begins today'),
(25, 'Fear is an illusion'),
(26, 'Growth requires discomfort'),
(27, 'Your thoughts become your reality'),
(28, 'Gratitude unlocks abundance'),
(29, 'Justice demands courage'),
(30, 'Peace comes from purpose'),
(31, 'Love is the highest power'),
(32, 'Dreams require discipline'),
(33, 'Wisdom requires silence'),
(34, 'Change begins within'),
(35, 'Influence is earned, not given'),
(36, 'Your past does not define your future'),
(37, 'Community makes you stronger'),
(38, 'Wealth without purpose is hollow'),
(39, 'Authenticity attracts alignment'),
(40, 'Your health is your wealth'),
(41, 'Servants become leaders'),
(42, 'Excellence is in the details'),
(43, 'Faith without works is dead'),
(44, 'Your impact outlives your years'),
(45, 'Wisdom comes from experience'),
(46, 'Purpose creates persistence'),
(47, 'Character is destiny'),
(48, 'Legacy is your masterpiece'),
(49, 'Truth sets you free'),
(50, 'Walk in wisdom. Build with purpose. Leave a legacy.');

-- Seed sample products
INSERT INTO public.products (name, description, image_url, price, category) VALUES
('The Chancellor Watch', 'Precision timepiece embodying executive elegance and timeless craftsmanship', '/bevan-shelton-watch.png', 'Upon Request', 'Luxury'),
('The Chancellor Eyewear', 'Premium glasses that blend sophistication with clarity of vision', '/bevan-shelton-eyewear.png', 'Upon Request', 'Luxury'),
('Legacy Collection', 'Exclusive curated items representing excellence and purpose', '/chancellor-crest.png', 'Upon Request', 'Luxury');
