(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n||0));
if(!q('link[data-acquisition-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='acquisition.css?v=20260811-1';l.dataset.acquisitionStyles='1';document.head.appendChild(l)}
let loading=false;
function ensurePanel(){const view=q('#growthView');if(!view||q('#acquisitionPanel'))return;view.insertAdjacentHTML('afterbegin','<section class="panel acquisition-panel" id="acquisitionPanel"><div class="panel-heading"><div><p class="eyebrow">Lead acquisition engine</p><h2>Source → Conversation → Audit → Payment → Revenue</h2><p class="muted">Track which campaigns and referral partners bring buyers, not merely clicks.</p></div><span class="badge" id="acqRevenueBadge">R0 attributed</span></div><div class="metric-grid"><div class="metric"><small>Visitors</small><strong id="acqVisitors">0</strong></div><div class="metric"><small>Chancellor conversations</small><strong id="acqConversations">0</strong></div><div class="metric"><small>WhatsApp leads</small><strong id="acqWhatsApp">0</strong></div><div class="metric"><small>Audits created</small><strong id="acqAudits">0</strong></div><div class="metric"><small>Paid audits</small><strong id="acqPaid">0</strong></div><div class="metric"><small>Attributed revenue</small><strong id="acqRevenue">R0</strong></div></div><section class="panel"><p class="eyebrow">Ready-to-share campaign links</p><h3>Tracked entry points</h3><div class="acq-links" id="acqLinks"></div><div class="offer-admin-form" style="margin-top:16px"><label>Referral / partner code<input id="acqRefCode" placeholder="e.g. FNB-JHB or TSietsi"></label><button class="button compact" id="buildRefLink">Copy partner referral link</button><p class="status" id="acqRefStatus"></p></div></section><section class="panel"><p class="eyebrow">Campaign performance</p><h3>Which sources are converting?</h3><div class="acq-channel-table" id="acqChannels"></div></section><section class="panel"><p class="eyebrow">Fresh WhatsApp leads</p><h3>Campaign enquiries</h3><div class="acq-leads" id="acqRecentLeads"></div></section></section>')}
const base=()=>String(location.origin||'https://the-chancellor.onrender.com').replace(/\/$/,'');
function campaignLinks(){return [
 ['Funding Ready',`${base()}/campaign.html?focus=funding&utm_source=facebook&utm_medium=social&utm_campaign=funding_ready`],
 ['Tender Ready',`${base()}/campaign.html?focus=tender&utm_source=facebook&utm_medium=social&utm_campaign=tender_ready`],
 ['Investor Ready',`${base()}/campaign.html?focus=investor&utm_source=linkedin&utm_medium=social&utm_campaign=investor_ready`],
 ['Business Growth',`${base()}/campaign.html?focus=growth&utm_source=whatsapp&utm_medium=direct-message&utm_campaign=business_growth`],
 ['Referral',`${base()}/campaign.html?focus=growth&utm_source=referral&utm_medium=partner&utm_campaign=referral`],
 ['Radio / Interview',`${base()}/campaign.html?focus=growth&utm_source=radio&utm_medium=broadcast&utm_campaign=radio_call_to_action`]
]}
function leadPhone(v=''){let d=String(v).replace(/\D/g,'');if(d.startsWith('0'))d=`27${d.slice(1)}`;return d}
async function copy(text,button){try{await navigator.clipboard.writeText(text);if(button){const old=button.textContent;button.textContent='Copied ✓';setTimeout(()=>button.textContent=old,1200)}return true}catch{return false}}
function bindReferral(){const b=q('#buildRefLink');if(!b)return;b.onclick=async()=>{const raw=q('#acqRefCode').value.trim(),st=q('#acqRefStatus');if(!raw){st.textContent='Enter a referral or partner code first.';st.className='status error';return}const code=raw.replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,60),url=`${base()}/campaign.html?focus=growth&utm_source=referral&utm_medium=partner&utm_campaign=referral&ref=${encodeURIComponent(code)}`;if(await copy(url,b)){st.textContent=`Referral link copied for ${code}. Revenue from this code will appear separately in acquisition reporting.`;st.className='status'}else{st.textContent=url;st.className='status'}}}
function render(d){const m=d.metrics||{};q('#acqVisitors').textContent=m.visitors||0;q('#acqConversations').textContent=m.conversations||0;q('#acqWhatsApp').textContent=m.whatsappLeads||0;q('#acqAudits').textContent=m.audits||0;q('#acqPaid').textContent=m.paidAudits||0;q('#acqRevenue').textContent=money(m.attributedRevenue||0);q('#acqRevenueBadge').textContent=`${money(m.attributedRevenue||0)} attributed`;
 q('#acqLinks').innerHTML=campaignLinks().map(([label,url])=>`<div class="acq-link"><b>${esc(label)}</b><code>${esc(url)}</code><button class="button compact copy-acq" data-url="${esc(url)}">Copy link</button></div>`).join('');
 q('#acqChannels').innerHTML=(d.channels||[]).length?`<div class="acq-channel-row"><div><b>Source / campaign</b></div><b>Visitors</b><b>Talks</b><b>Audits</b><b>Paid</b><b>Follow-on</b><b>Revenue</b></div>${d.channels.map(r=>`<div class="acq-channel-row"><div><b>${esc(r.source)}</b><small>${esc(r.medium)} · ${esc(r.campaign)}${r.referralCode?` · ref: ${esc(r.referralCode)}`:''}</small></div><span>${r.visitors}</span><span>${r.conversations}</span><span>${r.audits}</span><span>${r.paidAudits}</span><span>${r.followOnSales}</span><b>${money(r.totalRevenue)}</b></div>`).join('')}`:'<p class="muted">No attributed traffic yet.</p>';
 q('#acqRecentLeads').innerHTML=(d.recentLeads||[]).length?d.recentLeads.map(l=>{const digits=leadPhone(l.phone),msg=`Hi ${String(l.name||'').split(' ')[0]||'there'}, this is The Chancellor's Business Growth Desk following up on your enquiry${l.businessName?` for ${l.businessName}`:''}.`;return `<div class="acq-lead"><div><b>${esc(l.businessName||l.name)}</b><small>${esc(l.name)} · ${esc(l.goal||'Business growth enquiry')}</small></div><span>${esc(l.touch?.source||'direct')}<small> · ${esc(l.touch?.campaign||'organic')}${l.touch?.referralCode?` · ${esc(l.touch.referralCode)}`:''}</small></span>${digits?`<a class="button compact" target="_blank" rel="noopener" href="https://wa.me/${digits}?text=${encodeURIComponent(msg)}">WhatsApp</a>`:'<span>No mobile</span>'}</div>`}).join(''):'<p class="muted">No campaign lead captures yet.</p>';
 qa('.copy-acq').forEach(b=>b.onclick=()=>copy(b.dataset.url,b));bindReferral()}
async function load(){ensurePanel();if(loading)return;loading=true;try{const r=await fetch('/api/admin/acquisition');if(r.status===401)return;if(!r.ok)throw new Error();render(await r.json())}catch{q('#acqChannels').innerHTML='<p class="status error">Acquisition reporting could not be loaded.</p>'}finally{loading=false}}
ensurePanel();const dash=q('#adminDash');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(load,300)}).observe(dash,{attributes:true,attributeFilter:['class']});qa('.command-tabs button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='growthView')setTimeout(load,100)}));setTimeout(()=>{if(dash&&!dash.classList.contains('hidden'))load()},1000);
})();
