(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n||0));
if(!q('link[data-activation-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='activation.css?v=20260811-1';l.dataset.activationStyles='1';document.head.appendChild(l)}
let loading=false,data=null;
const base=()=>String(location.origin||'https://the-chancellor.onrender.com').replace(/\/$/,'');
function tracked(c,ref=''){const p=new URLSearchParams({focus:c.focus,utm_source:c.source,utm_medium:c.medium,utm_campaign:c.campaign});if(ref)p.set('ref',ref);return `${base()}/campaign.html?${p.toString()}`}
async function copy(text,btn){try{await navigator.clipboard.writeText(text);if(btn){const old=btn.textContent;btn.textContent='Copied ✓';setTimeout(()=>btn.textContent=old,1200)}return true}catch{return false}}
function ensurePanel(){const view=q('#growthView');if(!view||q('#activationPanel'))return;view.insertAdjacentHTML('afterbegin',`<section class="panel activation-panel" id="activationPanel"><div class="panel-heading"><div><p class="eyebrow">Campaign activation desk</p><h2>Put prospects into the funnel today</h2><p class="muted">Copy a campaign, use its tracked link, record the activity, then let acquisition reporting show what converts.</p></div><span class="badge" id="activationCompletion">0% today</span></div><div class="metric-grid"><div class="metric"><small>New approaches</small><strong id="actOutreach">0 / 30</strong></div><div class="metric"><small>Follow-ups</small><strong id="actFollowup">0 / 10</strong></div><div class="metric"><small>Sales conversations</small><strong id="actConversation">0 / 5</strong></div><div class="metric"><small>Quotes / offers</small><strong id="actQuote">0 / 2</strong></div><div class="metric"><small>Close attempts</small><strong id="actClose">0 / 1</strong></div></div><div class="activation-quick"><button class="button compact act-log" data-activity="outreach">+ Outreach</button><button class="button compact act-log" data-activity="followup">+ Follow-up</button><button class="button compact act-log" data-activity="conversation">+ Conversation</button><button class="button compact act-log" data-activity="quote">+ Quote</button><button class="button compact dark act-log" data-activity="close">+ Close attempt</button><span id="activationStatus" class="status"></span></div><section class="panel"><p class="eyebrow">Ready-to-send campaigns</p><h3>Copy. Post. Send. Track.</h3><div id="activationCampaigns" class="activation-campaigns"></div></section><section class="panel"><div class="panel-heading"><div><p class="eyebrow">Referral partner programme</p><h3>Partners who can bring paying clients</h3></div></div><form id="partnerForm" class="partner-form"><label>Partner / organisation<input name="name" required></label><label>Referral code<input name="code" required placeholder="e.g. PARTNER-JHB"></label><label>Email<input name="email" type="email"></label><label>Mobile<input name="phone"></label><label>Agreed commission %<input name="commissionPercent" type="number" min="0" max="50" step="0.5" value="0"></label><label class="wide">Agreement note<textarea name="agreementNote" rows="2" placeholder="Only record a commission once it has actually been agreed."></textarea></label><button class="button compact" type="submit">Add partner</button><p class="status" id="partnerStatus"></p></form><div id="partnerList" class="partner-list"></div></section></section>`)}
function progress(id,val,target){const el=q(id);if(el)el.textContent=`${val||0} / ${target}`}
function campaignCard(c){const url=tracked(c),pack={facebook:`${c.facebook}\n\n${url}`,whatsapp:`${c.whatsapp}\n\n${url}`,linkedin:`${c.linkedin}\n\n${url}`,radio:`${c.radio}\n\n${url}`};return `<article class="activation-card" data-id="${esc(c.id)}"><div class="activation-card-head"><div><p class="eyebrow">${esc(c.name)}</p><h3>${esc(c.hook)}</h3></div><button class="button compact copy-link" data-text="${esc(url)}">Copy tracked link</button></div><div class="activation-copy-grid">${Object.entries(pack).map(([channel,text])=>`<div class="activation-copy"><b>${esc(channel[0].toUpperCase()+channel.slice(1))}</b><p>${esc(text)}</p><div><button class="button compact copy-copy" data-channel="${esc(channel)}" data-text="${esc(text)}">Copy copy</button><button class="button compact dark mark-used" data-channel="${esc(channel)}">Mark used</button></div></div>`).join('')}</div></article>`}
function partnerCard(p){const url=`${base()}/campaign.html?focus=growth&utm_source=referral&utm_medium=partner&utm_campaign=referral&ref=${encodeURIComponent(p.code)}`;return `<div class="partner-row" data-id="${esc(p.id)}"><div><b>${esc(p.name)}</b><small>${esc(p.code)} · ${esc(p.status||'Prospect')}</small></div><span><small>Paid clients</small><b>${p.paidClients||0}</b></span><span><small>Attributed</small><b>${money(p.attributedRevenue||0)}</b></span><span><small>Agreed %</small><input class="partner-rate" type="number" min="0" max="50" step="0.5" value="${Number(p.commissionPercent||0)}"></span><span><small>Indicative</small><b>${money(p.indicativeCommission||0)}</b></span><button class="button compact partner-link" data-url="${esc(url)}">Copy link</button><button class="button compact partner-save">Save</button></div>`}
async function logActivity(activity,campaignId='',channel='',quantity=1,note=''){const st=q('#activationStatus');st.className='status';st.textContent='Recording activity…';const r=await fetch('/api/admin/activation/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activity,campaignId,channel,quantity,note})});const j=await r.json();if(!r.ok){st.textContent=j.error||'Could not record activity.';st.className='status error';return false}st.textContent='Activity recorded.';await load();return true}
function bind(){
 qa('.act-log').forEach(b=>b.onclick=()=>logActivity(b.dataset.activity));
 qa('.copy-link,.copy-copy').forEach(b=>b.onclick=()=>copy(b.dataset.text,b));
 qa('.mark-used').forEach(b=>b.onclick=()=>{const card=b.closest('.activation-card');logActivity('outreach',card.dataset.id,b.dataset.channel,1,`Campaign copy used on ${b.dataset.channel}`)});
 qa('.partner-link').forEach(b=>b.onclick=()=>copy(b.dataset.url,b));
 qa('.partner-save').forEach(b=>b.onclick=async()=>{const row=b.closest('.partner-row'),rate=row.querySelector('.partner-rate').value;b.disabled=true;const r=await fetch(`/api/admin/referral-partners/${row.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({commissionPercent:rate})});b.disabled=false;if(r.ok)load()});
 const pf=q('#partnerForm');if(pf&&!pf.dataset.bound){pf.dataset.bound='1';pf.addEventListener('submit',async e=>{e.preventDefault();const st=q('#partnerStatus'),btn=pf.querySelector('button');btn.disabled=true;st.className='status';st.textContent='Adding partner…';const r=await fetch('/api/admin/referral-partners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(pf)))});const j=await r.json();btn.disabled=false;if(!r.ok){st.textContent=j.error||'Partner could not be added.';st.className='status error';return}st.textContent='Partner added. Referral link is ready.';pf.reset();pf.querySelector('[name="commissionPercent"]').value='0';load()})}
}
function render(d){data=d;const daily=d.daily||{},c=daily.counts||{},t=daily.targets||{};progress('#actOutreach',c.outreach,t.outreach||30);progress('#actFollowup',c.followup,t.followup||10);progress('#actConversation',c.conversation,t.conversation||5);progress('#actQuote',c.quote,t.quote||2);progress('#actClose',c.close,t.close||1);q('#activationCompletion').textContent=`${daily.completion||0}% today`;q('#activationCampaigns').innerHTML=(d.campaigns||[]).map(campaignCard).join('');q('#partnerList').innerHTML=(d.partners||[]).length?(d.partners||[]).map(partnerCard).join(''):'<p class="muted">No referral partners registered yet.</p>';bind()}
async function load(){ensurePanel();if(loading)return;loading=true;try{const r=await fetch('/api/admin/activation');if(r.status===401)return;if(!r.ok)throw new Error();render(await r.json())}catch{q('#activationCampaigns').innerHTML='<p class="status error">Campaign Activation Desk could not be loaded.</p>'}finally{loading=false}}
ensurePanel();const dash=q('#adminDash');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(load,300)}).observe(dash,{attributes:true,attributeFilter:['class']});qa('.command-tabs button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='growthView')setTimeout(load,100)}));setTimeout(()=>{if(dash&&!dash.classList.contains('hidden'))load()},1000);
})();
