const $=s=>document.querySelector(s),messages=$('#messages'),quick=$('#quick'),form=$('#chatForm'),input=$('#chatInput');let history=[],voiceOn=false,aiVoice=false;
function add(text,type,id){const el=document.createElement('div');el.className=`message ${type}`;if(id)el.id=id;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
function offerAudit(){if(document.querySelector('.audit-conversion'))return;const wrap=document.createElement('div');wrap.className='message bot audit-conversion';wrap.innerHTML='<strong>Your next practical step</strong><br><span>Get a 100-point Business Readiness Audit for R500 and leave with a clear priority plan.</span>';const b=document.createElement('button');b.type='button';b.textContent='Start my R500 audit →';b.className='button compact';b.style.cssText='display:block;margin-top:12px;width:max-content;max-width:100%';b.addEventListener('click',()=>{const goal=$('#auditForm [name="goal"]');const last=[...history].reverse().find(x=>x.role==='user');if(goal&&!goal.value&&last)goal.value=last.content;document.querySelector('#audit').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#auditForm [name="name"]')?.focus(),500)});wrap.appendChild(b);messages.appendChild(wrap);messages.scrollTop=messages.scrollHeight}
async function speak(text){if(!voiceOn)return;if(aiVoice){try{const r=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(r.ok){const audio=new Audio(URL.createObjectURL(await r.blob()));await audio.play();return}}catch{}}if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/en-ZA/i.test(v.lang))||voices.find(v=>/en-GB/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang));u.rate=.92;u.pitch=.95;speechSynthesis.speak(u)}}
async function answer(text){text=text.trim();if(!text)return;add(text,'user');history.push({role:'user',content:text});input.value='';quick.hidden=true;const thinking=add('The Chancellor is considering that…','bot thinking','thinking');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-8)})});const data=await r.json();if(!r.ok)throw new Error(data.error);thinking.remove();add(data.reply,'bot');history.push({role:'assistant',content:data.reply});const turnCount=history.filter(x=>x.role==='assistant').length;if(/R500|readiness audit|audit/i.test(data.reply)||turnCount>=3)offerAudit();speak(data.reply)}catch(e){thinking.textContent=e.message||'I could not respond just now. Please try again.'}}
quick.addEventListener('click',e=>{if(e.target.tagName==='BUTTON')answer(e.target.textContent)});form.addEventListener('submit',e=>{e.preventDefault();answer(input.value)});$('#resetChat').addEventListener('click',()=>{history=[];messages.innerHTML='<div class="message bot">Welcome. Which opportunity matters most to your business right now?</div>';quick.hidden=false;if('speechSynthesis'in window)speechSynthesis.cancel()});
$('#voiceToggle').addEventListener('click',()=>{voiceOn=!voiceOn;const b=$('#voiceToggle');b.textContent=voiceOn?'Voice on':'Voice off';b.classList.toggle('active',voiceOn);if(voiceOn)speak("Voice is on. I'm ready when you are.")});
$('#micButton').addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Voice input is not supported by this browser. You can still type your answer.');return}const recognition=new SR();recognition.lang='en-ZA';recognition.interimResults=false;$('#micButton').textContent='●';recognition.onresult=e=>{input.value=e.results[0][0].transcript;input.focus()};recognition.onend=()=>{$('#micButton').textContent='🎙'};recognition.onerror=()=>{$('#micButton').textContent='🎙'};recognition.start()});
fetch('/api/status').then(r=>r.json()).then(s=>{aiVoice=Boolean(s.voice)}).catch(()=>{});
const readiness=[['registered','Is the business formally registered?'],['taxCompliant','Is tax compliance current?'],['bankAccount','Is there a dedicated business bank account?'],['financials','Are financial records current?'],['profile','Is the company profile current?'],['plan','Is there a current business plan?'],['market','Is the target customer clearly defined?'],['revenue','Does the business earn consistent revenue?'],['team','Are delivery roles and capacity clear?'],['opportunity','Is the immediate opportunity clearly defined?']];
$('#questions').innerHTML=readiness.map(([name,label])=>`<label>${label}<select name="${name}" required><option value="">Select</option><option value="yes">Yes</option><option value="no">Not yet</option></select></label>`).join('');
$('#auditForm').addEventListener('submit',async e=>{e.preventDefault();const status=$('#auditStatus'),button=e.currentTarget.querySelector('button[type="submit"]');status.className='status';status.textContent='Creating your private workspace…';button.disabled=true;const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/audits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.error);sessionStorage.setItem('newAccessCode',out.accessCode);status.innerHTML=`Workspace created. Your access code is <strong>${out.accessCode}</strong>. Save it now. Taking you to secure payment…`;setTimeout(()=>location.href='portal.html?new=1',900)}catch(err){status.className='status error';status.textContent=err.message;button.disabled=false}});
