(()=>{
const q=s=>document.querySelector(s),params=new URLSearchParams(location.search),focus=(params.get('focus')||params.get('campaign')||'growth').toLowerCase();
document.querySelectorAll('.crest-logo').forEach(img=>{img.src='/assets/the-chancellor-crest.svg?v=20260813-crest-direct-3';});
const variants={
  funding:{eyebrow:'Funding readiness starts before the application',headline:'Before you apply for funding, know what a funder will see.',lead:'Start with the R500 Business Readiness Audit to identify document, financial and positioning gaps before you spend time chasing the wrong funding opportunity.'},
  tender:{eyebrow:'Contract & tender readiness',headline:'Stop entering opportunities with gaps you could have fixed first.',lead:'Start with the R500 Business Readiness Audit to check capability, compliance, documents and evidence before deadline pressure starts.'},
  investor:{eyebrow:'Investor readiness',headline:'A good business still needs a credible investment story.',lead:'Start with the R500 Business Readiness Audit to clarify the opportunity, evidence, numbers, use of funds and investor narrative before you pitch.'},
  startup:{eyebrow:'Start with structure, not noise',headline:'Turn the business idea into an organised next move.',lead:'Start with the R500 Business Readiness Audit to clarify the model, target customer, immediate risks and the first business assets you actually need.'},
  growth:{eyebrow:'Build. Position. Fund. Grow.',headline:'Find the next practical move for your business.',lead:'Start with the R500 Business Readiness Audit. We identify the gaps between your business and its next opportunity, then recommend the smallest sensible next move.'}
};
const v=variants[focus]||variants.growth;q('#campaignEyebrow').textContent=v.eyebrow;q('#campaignHeadline').textContent=v.headline;q('#campaignLead').textContent=v.lead;
function carried(path){const p=new URLSearchParams(location.search);if(!p.get('utm_campaign'))p.set('utm_campaign',focus);if(!p.get('utm_source'))p.set('utm_source','campaign-page');if(!p.get('utm_medium'))p.set('utm_medium','landing-page');const [base,hash]=path.split('#');return `${base||'/'}?${p.toString()}${hash?`#${hash}`:''}`}
q('#talkCta').href=carried('/#adviser');q('#auditCta').href=carried('/#audit');
q('#campaignLeadForm').addEventListener('submit',async e=>{e.preventDefault();const st=q('#campaignLeadStatus'),button=e.currentTarget.querySelector('button');button.disabled=true;st.className='status';st.textContent='Saving your enquiry…';const form=Object.fromEntries(new FormData(e.currentTarget));const acq=window.ChancellorAcquisition||{};try{const r=await fetch('/api/acquisition/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,visitorId:acq.visitorId,touch:acq.touch})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save your enquiry.');await acq.track?.('whatsapp_click',{label:'R500 audit campaign WhatsApp'});const first=String(form.name||'').trim().split(/\s+/)[0]||'there';const need=form.goal||'I want to understand whether the R500 Business Readiness Audit is the right next step for my business';const msg=`Hi, I am ${first}${form.businessName?` from ${form.businessName}`:''}. I found The Chancellor's Business Growth Desk through the ${focus} campaign. I am interested in the R500 Business Readiness Audit. My immediate need is: ${need}.`;const number='27662982213';st.textContent='Enquiry saved. Opening WhatsApp…';setTimeout(()=>{location.href=`https://wa.me/${number}?text=${encodeURIComponent(msg)}`},350)}catch(err){st.textContent=err.message;st.className='status error';button.disabled=false}});
})();
