(()=>{
const messages=document.getElementById('messages'),form=document.getElementById('chatForm'),input=document.getElementById('chatInput'),quick=document.getElementById('quick');
if(!messages||!form||!input)return;
let sessionId='';try{sessionId=localStorage.getItem('chancellorConciergeSession')||crypto.randomUUID();localStorage.setItem('chancellorConciergeSession',sessionId)}catch{sessionId=String(Date.now())+'-'+Math.random().toString(16).slice(2)}
function add(text,type='bot'){const el=document.createElement('div');el.className=`message ${type}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
function addAction(action){if(!action)return;const wrap=document.createElement('div');wrap.className='message bot concierge-action';const b=document.createElement('button');b.className='button compact';b.type='button';b.textContent=action.label||'Continue';b.onclick=()=>{if(action.type==='audit'){const p=action.prefill||{};for(const [k,v] of Object.entries(p)){const el=document.querySelector(`#auditForm [name="${CSS.escape(k)}"]`);if(el&&!el.value&&v)el.value=v}document.getElementById('audit')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector('#auditForm [name="name"]')?.focus(),500);return}if(action.href)location.href=action.href};wrap.innerHTML='<strong>Next step</strong><br>';wrap.appendChild(b);messages.appendChild(wrap);messages.scrollTop=messages.scrollHeight}
async function send(text){text=String(text||'').trim();if(!text)return;add(text,'user');input.value='';if(quick)quick.hidden=true;const thinking=add('The Chancellor is working on your next step…','bot thinking');try{const r=await fetch('/api/concierge/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,message:text})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');thinking.remove();add(j.reply,'bot');if(j.action)addAction(j.action);if(j.leadCreated)try{sessionStorage.setItem('chancellorCrmLeadId',j.leadId||'')}catch{};window.dispatchEvent(new CustomEvent('chancellor:concierge',{detail:j}))}catch(e){thinking.textContent=e.message||'I could not continue just now. Please try again.'}}
form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();send(input.value)},true);
if(quick)quick.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;e.preventDefault();e.stopImmediatePropagation();send(e.target.textContent)},true);
const reset=document.getElementById('resetChat');if(reset)reset.addEventListener('click',()=>{try{localStorage.removeItem('chancellorConciergeSession')}catch{};sessionId=crypto.randomUUID();try{localStorage.setItem('chancellorConciergeSession',sessionId)}catch{}},true);
window.ChancellorConcierge={send,getSessionId:()=>sessionId};
})();