const state={leads:[],activities:[],metrics:null,sources:[]};
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw Object.assign(new Error(data.error||'Request failed'),{status:res.status});return data}
function showLogin(message=''){ $('loginPanel').classList.remove('hidden'); $('crmApp').classList.add('hidden'); $('loginMessage').textContent=message; }
function showApp(){ $('loginPanel').classList.add('hidden'); $('crmApp').classList.remove('hidden'); }
function scoreCard(label,value,target){const pct=Math.min(100,Math.round((Number(value||0)/target)*100));return `<div class="score-card"><div class="label">${label}</div><div class="value">${value}</div><div class="target">Target ${target}</div><div class="bar"><span style="width:${pct}%"></span></div></div>`}
function renderScoreboard(){const a=state.metrics.actual,t=state.metrics.targets;$('scoreboard').innerHTML=scoreCard('Approaches',a.approaches,t.approaches)+scoreCard('Follow-ups',a.followups,t.followups)+scoreCard('Conversations',a.conversations,t.conversations)+scoreCard('Proposals',a.proposals,t.proposals)+scoreCard('Closing attempts',a.closes,t.closes)+`<div class="score-card"><div class="label">Payments</div><div class="value">${a.payments}</div><div class="target">Cash received today</div></div><div class="score-card"><div class="label">Cash today</div><div class="value money">${money(a.cash)}</div><div class="target">Pipeline ${money(state.metrics.pipelineValue)}</div></div>`}
function row(lead){return `<tr><td><div class="lead-name">${esc(lead.businessName||lead.name||'Unnamed')}</div><div class="sub">${esc(lead.name)} ${lead.phone?`· ${esc(lead.phone)}`:''}</div></td><td>${esc(lead.source||'')}</td><td><span class="stage">${esc(lead.stage)}</span></td><td class="money">${money(lead.value)}</td><td>${esc(lead.nextAction||'—')}</td><td>${esc(lead.followUpDate||'—')}</td><td><div class="row-actions"><button data-log="${lead.id}">Log</button><button data-edit="${lead.id}" class="ghost">Advance</button></div></td></tr>`}
function renderLeads(){const q=$('searchInput').value.trim().toLowerCase();const leads=state.leads.filter(l=>!q||[l.name,l.businessName,l.phone,l.source,l.stage,l.need].join(' ').toLowerCase().includes(q));$('leadRows').innerHTML=leads.length?leads.map(row).join(''):`<tr><td colspan="7" class="sub">No leads yet. Add your first prospect above.</td></tr>`}
function renderActivities(){const names=Object.fromEntries(state.leads.map(l=>[l.id,l.businessName||l.name||'Lead']));$('activityLog').innerHTML=state.activities.length?state.activities.slice(0,30).map(a=>`<div class="activity-item"><div><div class="activity-type">${esc(a.type)}</div><div>${esc(names[a.leadId]||'Lead')}</div><div class="sub">${esc(a.note||'')}</div></div><div class="sub">${new Date(a.createdAt).toLocaleString('en-ZA')}${a.amount?`<br><span class="money">${money(a.amount)}</span>`:''}</div></div>`).join(''):`<div class="sub">No activity logged yet today.</div>`}
function renderStages(){const entries=Object.entries(state.metrics.stageCounts||{}).filter(([,v])=>v>0);$('stageTotals').innerHTML=(entries.length?entries:[['No leads',0]]).map(([stage,count])=>`<div class="stage-row"><span>${esc(stage)}</span><strong>${count}</strong></div>`).join('')+`<div class="stage-row"><span>Open pipeline value</span><strong class="money">${money(state.metrics.pipelineValue)}</strong></div><div class="stage-row"><span>Won value</span><strong class="money">${money(state.metrics.wonValue)}</strong></div>`}
function render(){renderScoreboard();renderLeads();renderActivities();renderStages()}
async function load(){try{const data=await api('/api/crm');Object.assign(state,data);showApp();$('leadSource').innerHTML=state.sources.map(s=>`<option>${esc(s)}</option>`).join('');render()}catch(e){if(e.status===401)return showLogin();throw e}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/auth/admin',{method:'POST',body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});await load()}catch(err){showLogin(err.message)}});
$('logoutBtn').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});showLogin()});
$('refreshBtn').addEventListener('click',load);
$('toggleLeadForm').addEventListener('click',()=> $('leadForm').classList.toggle('hidden'));
$('leadForm').addEventListener('submit',async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());try{await api('/api/crm/leads',{method:'POST',body:JSON.stringify(body)});e.currentTarget.reset();await load()}catch(err){alert(err.message)}});
$('searchInput').addEventListener('input',renderLeads);
$('leadRows').addEventListener('click',async e=>{const log=e.target.dataset.log,edit=e.target.dataset.edit;if(log){const lead=state.leads.find(l=>l.id===log);$('activityLeadId').value=log;$('activityTitle').textContent=`Log activity — ${lead?.businessName||lead?.name||'Lead'}`;$('activityType').value='approach';$('activityAmount').value='';$('activityNote').value='';$('activityDialog').showModal()}if(edit){const lead=state.leads.find(l=>l.id===edit);const stages=['NEW','CONTACTED','REPLIED','CONVERSATION','AUDIT OFFERED','PAID','PROPOSAL SENT','WON','FOLLOW-UP','LOST'];const current=Math.max(0,stages.indexOf(lead.stage));const next=stages[Math.min(current+1,stages.length-1)];if(confirm(`Move ${lead.businessName||lead.name} from ${lead.stage} to ${next}?`)){await api(`/api/crm/leads/${edit}`,{method:'PATCH',body:JSON.stringify({stage:next})});await load()}}});
$('activityForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return; e.preventDefault();const leadId=$('activityLeadId').value;try{await api(`/api/crm/leads/${leadId}/activity`,{method:'POST',body:JSON.stringify({type:$('activityType').value,amount:$('activityAmount').value,note:$('activityNote').value})});$('activityDialog').close();await load()}catch(err){alert(err.message)}});
load().catch(err=>showLogin(err.message));
