(()=>{
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n||0));
if(!q('link[data-delivery-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='delivery.css?v=20260811-1';l.dataset.deliveryStyles='1';document.head.appendChild(l)}
function panel(){const dash=q('#dashboard');if(!dash||q('#deliveryPanel'))return;q('#logout')?.insertAdjacentHTML('beforebegin','<section class="panel" id="deliveryPanel"><p class="eyebrow">Step 5 · Paid work</p><h2>Your active assignments</h2><p>Once a follow-on service is paid, its production status, deadline and final files appear here.</p><div id="deliveryList" class="delivery-list"><p class="muted">No paid assignment has started yet.</p></div></section>')}
function dateText(v){if(!v)return'Not set';return new Date(v).toLocaleDateString('en-ZA',{year:'numeric',month:'short',day:'numeric'})}
function renderAssignment(a){const overdue=a.status!=='Completed'&&a.deadline&&new Date(a.deadline).getTime()<Date.now();const checks=(a.checklist||[]).map(x=>`<div class="delivery-check ${['Approved','Received','Not required'].includes(x.status)?'done':''}"><span>${esc(x.label)}</span><span class="badge">${esc(x.status)}</span></div>`).join('');const files=(a.files||[]).length?(a.files||[]).map(f=>`<div class="delivery-file"><span><b>${esc(f.originalName)}</b><small> · ${Math.max(1,Math.round(Number(f.size||0)/1024))} KB</small></span><a class="button compact" href="/api/client/deliverables/${encodeURIComponent(f.id)}/download">Download</a></div>`).join(''):'<p class="muted">No final files have been released yet.</p>';return `<article class="delivery-card"><div class="delivery-head"><div><p class="eyebrow">${esc(a.status)}</p><h3>${esc(a.service)}</h3><p>${money(a.amount)}</p></div><div class="delivery-progress"><strong>${Number(a.progress||0)}%</strong><small>Progress</small><div class="progress-track"><i style="width:${Math.max(0,Math.min(100,Number(a.progress||0)))}%"></i></div></div></div><div class="delivery-meta"><span><small>Started</small><b>${dateText(a.startedAt)}</b></span><span><small>Target date</small><b class="${overdue?'delivery-overdue':''}">${dateText(a.deadline)}${overdue?' · overdue':''}</b></span><span><small>Status</small><b>${esc(a.status)}</b></span></div>${a.clientMessage?`<div class="delivery-message"><b>Growth Desk update</b><p>${esc(a.clientMessage)}</p></div>`:''}<h4>Information checklist</h4><div class="delivery-checklist">${checks||'<p class="muted">No checklist items.</p>'}</div><h4>Final delivery files</h4><div class="delivery-files">${files}</div></article>`}
async function loadDelivery(){panel();const box=q('#deliveryList');if(!box)return;try{const r=await fetch('/api/client/assignments');if(r.status===401)return;if(!r.ok)throw new Error();const d=await r.json();box.innerHTML=(d.assignments||[]).length?d.assignments.slice().reverse().map(renderAssignment).join(''):'<p class="muted">No paid assignment has started yet. When a follow-on offer is paid, it will appear here automatically.</p>'}catch{box.innerHTML='<p class="status error">Assignment status could not be loaded.</p>'}}
panel();const dash=q('#dashboard');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(loadDelivery,300)}).observe(dash,{attributes:true,attributeFilter:['class']});setTimeout(()=>{if(dash&&!dash.classList.contains('hidden'))loadDelivery()},1000);setInterval(()=>{if(dash&&!dash.classList.contains('hidden'))loadDelivery()},30000);
})();
