(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let loading=false;
function ensurePanel(){const view=q('#growthView');if(!view||q('#followupPanel'))return;view.insertAdjacentHTML('afterbegin','<section class="panel" id="followupPanel"><div class="panel-heading"><div><p class="eyebrow">Revenue follow-up engine</p><h2>Who needs attention now</h2><p class="muted">The system prepares the next action. You decide whether and when to contact the client.</p></div><button class="button compact" id="refreshFollowups">Refresh queue</button></div><div class="metric-grid"><div class="metric"><small>Open now</small><strong id="fuOpen">0</strong></div><div class="metric"><small>Critical</small><strong id="fuCritical">0</strong></div><div class="metric"><small>High priority</small><strong id="fuHigh">0</strong></div><div class="metric"><small>Snoozed</small><strong id="fuSnoozed">0</strong></div></div><div id="followupQueue" class="delivery-list"><p class="muted">Loading follow-up queue…</p></div></section>');q('#refreshFollowups').onclick=()=>load(true)}
function isVisible(t){if(t.status==='Done')return false;if(t.status==='Snoozed'&&t.snoozedUntil&&new Date(t.snoozedUntil).getTime()>Date.now())return false;return t.status==='Open'}
function taskCard(t){const due=t.dueAt?new Date(t.dueAt).toLocaleString('en-ZA'):'Now',p=String(t.priority||'medium').toUpperCase(),contact=t.contact||{};return `<article class="delivery-card followup-card" data-id="${esc(t.id)}"><div class="delivery-head"><div><p class="eyebrow">${esc(p)} · ${esc(t.type||'follow-up')}</p><h3>${esc(t.title)}</h3><p>${esc(t.message)}</p><small>${esc(t.businessName||t.name||'Client')} · Due ${esc(due)}</small></div><span class="badge">${esc(t.status)}</span></div><div class="source-meta"><b>Recommended next action</b><p>${esc(t.recommendedAction||'Review and decide the next action.')}</p></div><div class="production-actions">${contact.whatsapp?`<a class="button compact" target="_blank" rel="noopener" href="${esc(contact.whatsapp)}">WhatsApp</a>`:''}${contact.email?`<a class="button compact dark" href="${esc(contact.email)}">Email</a>`:''}<button class="button compact followup-copy" data-message="${esc(contact.message||'')}">Copy message</button><button class="button compact followup-snooze">Snooze 24h</button><button class="button compact followup-done">Done</button></div><p class="status followup-status"></p></article>`}
async function patch(card,body){const st=card.querySelector('.followup-status');st.textContent='Saving…';const r=await fetch(`/api/admin/followups/${card.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let j={};try{j=await r.json()}catch{}if(!r.ok){st.textContent=j.error||'Could not update follow-up.';st.className='status error';return false}return true}
async function load(force=false){ensurePanel();if(loading)return;loading=true;try{const r=await fetch(force?'/api/admin/followups/scan':'/api/admin/followups',{method:force?'POST':'GET'});if(r.status===401)return;if(!r.ok)throw new Error();const d=await r.json(),m=d.metrics||{};q('#fuOpen').textContent=m.open||0;q('#fuCritical').textContent=m.critical||0;q('#fuHigh').textContent=m.high||0;q('#fuSnoozed').textContent=m.snoozed||0;const tasks=(d.tasks||[]).filter(isVisible);q('#followupQueue').innerHTML=tasks.length?tasks.map(taskCard).join(''):'<p class="muted">Nothing requires follow-up right now.</p>';qa('.followup-card').forEach(card=>{card.querySelector('.followup-copy').onclick=async e=>{try{await navigator.clipboard.writeText(e.currentTarget.dataset.message||'');card.querySelector('.followup-status').textContent='Message copied.'}catch{card.querySelector('.followup-status').textContent='Copy is unavailable on this browser.'}};card.querySelector('.followup-snooze').onclick=async()=>{if(await patch(card,{action:'snooze',hours:24}))load()};card.querySelector('.followup-done').onclick=async()=>{if(await patch(card,{action:'done'}))load()}})}catch{q('#followupQueue').innerHTML='<p class="status error">Follow-up queue could not be loaded.</p>'}finally{loading=false}}
ensurePanel();const dash=q('#adminDash');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(load,300)}).observe(dash,{attributes:true,attributeFilter:['class']});qa('.command-tabs button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='growthView')setTimeout(load,120)}));setInterval(()=>{if(dash&&!dash.classList.contains('hidden')&&!q('#growthView')?.classList.contains('hidden'))load()},5*60*1000);setTimeout(load,1100);
})();
