const crypto=require('node:crypto');
const store=require('./store');
const {normalise,hashSecret,verifySecret,accessCode}=require('./core');
const db=()=>store.read();
const now=()=>new Date().toISOString();
const safeAccount=a=>({id:a.id,accountNumber:a.accountNumber,name:a.name,accountType:a.accountType,contactName:a.contactName,email:a.email,phone:a.phone,status:a.status,benefitCode:a.benefitCode,planName:a.planName,seats:Number(a.seats||0),monthlyCaseAllowance:Number(a.monthlyCaseAllowance||0),slaHours:Number(a.slaHours||0),monthlyFee:Number(a.monthlyFee||0),contractStart:a.contractStart||null,contractEnd:a.contractEnd||null,invoiceStatus:a.invoiceStatus||'Not invoiced',notes:a.publicNotes||'',createdAt:a.createdAt,updatedAt:a.updatedAt});
function usage(accountId){const d=db();const audits=(d.audits||[]).filter(x=>x.institutionalAccountId===accountId),cases=(d.rescueCases||[]).filter(x=>x.institutionalAccountId===accountId);const paidAudits=audits.filter(a=>(d.payments||[]).some(p=>p.auditId===a.id&&String(p.status).toUpperCase()==='COMPLETE')).length;const resolved=cases.filter(c=>c.status==='Resolved').length;return{audits:audits.length,paidAudits,rescueCases:cases.length,resolved,beneficiaries:new Set([...audits.map(x=>String(x.email||'').toLowerCase()),...cases.map(x=>String(x.email||'').toLowerCase())].filter(Boolean)).size};}
module.exports=function registerInstitutionalRoutes(app){
  const requireAdmin=(req,res,next)=>req.session?.admin?next():res.status(401).json({error:'Administrator sign-in required.'});
  const requireInstitution=(req,res,next)=>req.session?.institutionId?next():res.status(401).json({error:'Institutional account sign-in required.'});
  app.post('/api/institutions/apply',(req,res)=>{const required=['name','accountType','contactName','email','phone'];if(required.some(k=>!normalise(req.body[k])))return res.status(400).json({error:'Complete the organisation and contact details.'});const email=normalise(req.body.email).toLowerCase().slice(0,180);const existing=(db().institutionalAccounts||[]).find(x=>x.email===email&&x.status!=='Declined');if(existing)return res.status(409).json({error:'An institutional application already exists for this email address.'});const record=store.insert('institutionalAccounts',{accountNumber:`INST-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,name:normalise(req.body.name).slice(0,180),accountType:normalise(req.body.accountType).slice(0,100),contactName:normalise(req.body.contactName).slice(0,140),email,phone:normalise(req.body.phone).slice(0,60),estimatedBeneficiaries:Math.max(0,Math.round(Number(req.body.estimatedBeneficiaries||0))),needs:normalise(req.body.needs).slice(0,1800),status:'Application received',benefitCode:null,planName:'Custom institutional package',seats:0,monthlyCaseAllowance:0,slaHours:0,monthlyFee:0,contractStart:null,contractEnd:null,invoiceStatus:'Not invoiced',accessHash:null});res.status(201).json({applicationNumber:record.accountNumber,status:record.status,message:'Institutional application received for commercial review.'});});
  app.post('/api/institutions/access',(req,res)=>{const email=normalise(req.body.email).toLowerCase(),code=normalise(req.body.code);const account=[...(db().institutionalAccounts||[])].reverse().find(x=>x.email===email&&x.accessHash&&verifySecret(code,x.accessHash));if(!account)return res.status(401).json({error:'Email or institutional access code is incorrect.'});if(!['Active','Pilot'].includes(account.status))return res.status(403).json({error:`Institutional account status: ${account.status}.`});req.session.institutionId=account.id;res.json({ok:true,account:safeAccount(account)});});
  app.post('/api/institutions/logout',(req,res)=>{delete req.session.institutionId;res.json({ok:true});});
  app.get('/api/institutions/portal',requireInstitution,(req,res)=>{const account=(db().institutionalAccounts||[]).find(x=>x.id===req.session.institutionId);if(!account)return res.status(404).json({error:'Institutional account not found.'});const d=db();const cases=(d.rescueCases||[]).filter(x=>x.institutionalAccountId===account.id).map(x=>({caseNumber:x.caseNumber,type:x.type,status:x.status,createdAt:x.createdAt,resolvedAt:x.resolvedAt||null}));const audits=(d.audits||[]).filter(x=>x.institutionalAccountId===account.id).map(x=>({businessName:x.businessName,status:x.status,salesStage:x.salesStage,createdAt:x.createdAt}));res.json({account:safeAccount(account),usage:usage(account.id),cases,audits});});
  app.post('/api/institutions/link-audit',(req,res)=>{if(!req.session?.clientId)return res.status(401).json({error:'Audit workspace required.'});const code=normalise(req.body.code).toUpperCase();if(!code)return res.json({ok:true,linked:false});const account=(db().institutionalAccounts||[]).find(x=>x.benefitCode===code&&['Active','Pilot'].includes(x.status));if(!account)return res.status(404).json({error:'Institutional benefit code is not active.'});store.update('audits',req.session.clientId,{institutionalAccountId:account.id,institutionalAccountNumber:account.accountNumber,institutionalBenefitCode:account.benefitCode});res.json({ok:true,linked:true,organisation:account.name});});
  app.post('/api/institutions/link-case',(req,res)=>{if(!req.session?.rescueCaseId)return res.status(401).json({error:'Rescue case workspace required.'});const code=normalise(req.body.code).toUpperCase();if(!code)return res.json({ok:true,linked:false});const account=(db().institutionalAccounts||[]).find(x=>x.benefitCode===code&&['Active','Pilot'].includes(x.status));if(!account)return res.status(404).json({error:'Institutional benefit code is not active.'});store.update('rescueCases',req.session.rescueCaseId,{institutionalAccountId:account.id,institutionalAccountNumber:account.accountNumber,institutionalBenefitCode:account.benefitCode});res.json({ok:true,linked:true,organisation:account.name});});
  app.get('/api/admin/institutions',requireAdmin,(_req,res)=>{const accounts=(db().institutionalAccounts||[]).map(a=>({...safeAccount(a),estimatedBeneficiaries:Number(a.estimatedBeneficiaries||0),needs:a.needs||'',usage:usage(a.id)}));const active=accounts.filter(a=>['Active','Pilot'].includes(a.status));res.json({metrics:{accounts:accounts.length,active:active.length,beneficiaries:active.reduce((s,a)=>s+a.usage.beneficiaries,0),monthlyContractValue:active.reduce((s,a)=>s+Number(a.monthlyFee||0),0)},accounts});});
  app.post('/api/admin/institutions/:id/activate',requireAdmin,(req,res)=>{const current=(db().institutionalAccounts||[]).find(x=>x.id===req.params.id);if(!current)return res.status(404).json({error:'Institutional account not found.'});const firstActivation=!current.accessHash;const code=firstActivation?accessCode():null;const benefitCode=current.benefitCode||`ORG-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;const status=['Active','Pilot'].includes(normalise(req.body.status))?normalise(req.body.status):'Pilot';const patch={status,benefitCode,planName:normalise(req.body.planName||'Custom institutional package').slice(0,140),seats:Math.max(0,Math.round(Number(req.body.seats||0))),monthlyCaseAllowance:Math.max(0,Math.round(Number(req.body.monthlyCaseAllowance||0))),slaHours:Math.max(0,Math.round(Number(req.body.slaHours||24))),monthlyFee:Math.max(0,Number(req.body.monthlyFee||0)),contractStart:normalise(req.body.contractStart)||now(),contractEnd:normalise(req.body.contractEnd)||null,invoiceStatus:normalise(req.body.invoiceStatus||'Not invoiced').slice(0,100),publicNotes:normalise(req.body.publicNotes).slice(0,800)};if(firstActivation)patch.accessHash=hashSecret(code);const updated=store.update('institutionalAccounts',current.id,patch);res.json({account:safeAccount(updated),accessCode:code,benefitCode,message:firstActivation?'Save and securely deliver this institutional access code; it is shown once.':'Institutional account updated.'});});
  app.patch('/api/admin/institutions/:id',requireAdmin,(req,res)=>{const current=(db().institutionalAccounts||[]).find(x=>x.id===req.params.id);if(!current)return res.status(404).json({error:'Institutional account not found.'});const patch={};if(req.body.status!==undefined){const s=normalise(req.body.status);if(!['Application received','Commercial review','Pilot','Active','Suspended','Closed','Declined'].includes(s))return res.status(400).json({error:'Invalid institutional account status.'});patch.status=s;}['invoiceStatus','contractStart','contractEnd','planName'].forEach(k=>{if(req.body[k]!==undefined)patch[k]=normalise(req.body[k]).slice(0,140)});['seats','monthlyCaseAllowance','slaHours'].forEach(k=>{if(req.body[k]!==undefined)patch[k]=Math.max(0,Math.round(Number(req.body[k]||0)))});if(req.body.monthlyFee!==undefined)patch.monthlyFee=Math.max(0,Number(req.body.monthlyFee||0));const updated=store.update('institutionalAccounts',current.id,patch);res.json({account:safeAccount(updated)});});
};
