(()=>{
if(!document.querySelector('link[data-offer-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='offers.css?v=20260811-1';l.dataset.offerStyles='1';document.head.appendChild(l)}
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(Number(n||0));
let loading=false,catalog=[];
function ensurePanel(){
  const view=q('#growthView');if(!view||q('#offerDeskPanel'))return;
  const panel=document.createElement('section');panel.className='panel';panel.id='offerDeskPanel';panel.innerHTML='<div class="panel-heading"><div><p class="eyebrow">Second money engine</p><h2>Audit → Offer → Accept → Pay</h2><p class="muted">Issue a clear, fixed-price next-step offer after the audit. The client sees it in their private portal and can accept and pay there.</p></div><span class="badge" id="offerRevenueBadge">R0 follow-on paid</span></div><div id="offerDesk"><p class="muted">Open the Growth Desk after signing in to load the offer queue.</p></div>';
  view.appendChild(panel);
}
function options(selected=''){return catalog.map(x=>`<option value="${esc(x.code)}" ${x.code===selected?'selected':''}>${esc(x.label)} — from ${money(x.floor)}</option>`).join('')}
function offerHistory(auditId,offers,payments){const list=offers.filter(o=>o.auditId===auditId).slice().reverse();if(!list.length)return '<small>No offer issued yet.</small>';return list.map(o=>{const paid=o.status==='Paid'||payments.some(p=>p.offerId===o.id&&String(p.status||'').toUpperCase()==='COMPLETE');return `<div class="file-row"><span><b>${esc(o.service)}</b> · ${money(o.amount)}<small> · ${esc(o.status)}</small></span><span class="badge">${paid?'PAID':esc(o.status)}</span></div>`}).join('')}
async function loadOfferDesk(){
  ensurePanel();const box=q('#offerDesk');if(!box||loading)return;loading=true;
  try{
    const [ar,cr,or]=await Promise.all([fetch('/api/admin'),fetch('/api/admin/offers/catalog'),fetch('/api/admin/offers')]);
    if(ar.status===401||cr.status===401||or.status===401){box.innerHTML='<p class="muted">Sign in to manage follow-on offers.</p>';return}
    if(!ar.ok||!cr.ok||!or.ok){box.innerHTML='<p class="status error">Offer Desk could not be loaded.</p>';return}
    const admin=await ar.json(),cat=await cr.json(),od=await or.json();catalog=cat.catalog||[];const audits=(admin.audits||[]).slice().reverse(),offers=od.offers||[],payments=od.payments||[];
    const paidRevenue=payments.filter(p=>String(p.status||'').toUpperCase()==='COMPLETE').reduce((s,p)=>s+Number(p.amount||0),0);q('#offerRevenueBadge').textContent=`${money(paidRevenue)} follow-on paid`;
    box.innerHTML=audits.length?audits.map(a=>`<article class="case-card" data-audit="${esc(a.id)}"><div class="case-summary"><div><small>${esc(a.salesStage||a.status)}</small><h3>${esc(a.businessName)}</h3><p>${esc(a.name)} · ${esc(a.email)} · ${esc(a.phone)}</p><p><b>Audit:</b> ${a.score}/100 · ${esc(a.band)} · <b>Goal:</b> ${esc(a.goal)}</p></div><div class="case-score"><strong>${money(a.quoteAmount||0)}</strong><span>${esc(a.recommendedService||'No quote yet')}</span></div></div><div class="offer-admin-form"><label>Service<select class="offer-service"><option value="">Choose service</option>${options()}</select></label><label>Quote amount<input class="offer-amount" type="number" min="5" step="50" placeholder="Amount in rand"></label><label>Valid for<select class="offer-days"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><label class="wide">Client-facing description<textarea class="offer-description" rows="2" placeholder="Why this is the sensible next step for this client"></textarea></label><label class="wide">Scope / deliverables<textarea class="offer-deliverables" rows="2" placeholder="What the client will receive"></textarea></label><button class="button compact send-offer">Send offer to client portal</button><p class="status offer-status"></p></div><details><summary>Offer history</summary><div class="file-list">${offerHistory(a.id,offers,payments)}</div></details></article>`).join(''):'<p>No audit leads yet.</p>';
    qa('.offer-service').forEach(sel=>sel.onchange=()=>{const card=sel.closest('.case-card'),item=catalog.find(x=>x.code===sel.value);if(item&&!card.querySelector('.offer-amount').value)card.querySelector('.offer-amount').value=item.defaultAmount});
    qa('.send-offer').forEach(btn=>btn.onclick=async()=>{const card=btn.closest('.case-card'),st=card.querySelector('.offer-status'),code=card.querySelector('.offer-service').value,amount=card.querySelector('.offer-amount').value,description=card.querySelector('.offer-description').value,deliverables=card.querySelector('.offer-deliverables').value,expiresInDays=card.querySelector('.offer-days').value;if(!code||!amount){st.textContent='Choose a service and quote amount.';st.className='status error';return}btn.disabled=true;btn.textContent='Sending…';const r=await fetch(`/api/admin/audits/${card.dataset.audit}/offers`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,amount,description,deliverables,expiresInDays})});const j=await r.json();if(!r.ok){st.textContent=j.error||'Offer could not be sent.';st.className='status error';btn.disabled=false;btn.textContent='Send offer to client portal';return}st.textContent=`Offer sent: ${j.offer.service} at ${money(j.offer.amount)}.`;st.className='status';setTimeout(loadOfferDesk,500)});
  }catch{box.innerHTML='<p class="status error">Offer Desk could not be loaded.</p>'}finally{loading=false}
}
ensurePanel();
const dash=q('#adminDash');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(loadOfferDesk,400)}).observe(dash,{attributes:true,attributeFilter:['class']});
qa('.command-tabs button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='growthView')setTimeout(loadOfferDesk,100)}));
setTimeout(loadOfferDesk,1000);
})();
