const store=require('./store');
const {normalise}=require('./core');
const db=()=>store.read();
const money=n=>Math.max(0,Math.round(Number(n||0)*100)/100);
const daysBetween=(a,b)=>{if(!a||!b)return null;const x=new Date(a),y=new Date(b);if(Number.isNaN(x.getTime())||Number.isNaN(y.getTime()))return null;return Math.max(0,Math.round((y-x)/86400000));};

function outcomePublic(x){if(!x)return null;return{id:x.id,caseId:x.caseId,caseNumber:x.caseNumber,outcomeType:x.outcomeType,resolutionSummary:x.resolutionSummary,amountBefore:x.amountBefore,amountAfter:x.amountAfter,valueSaved:x.valueSaved,debtReduced:x.debtReduced,assetValueProtected:x.assetValueProtected,taxExposureReduced:x.taxExposureReduced,cashFlowImprovement:x.cashFlowImprovement,jobsProtected:x.jobsProtected,clientConfirmed:Boolean(x.clientConfirmed),clientConfirmedAt:x.clientConfirmedAt||null,status:x.status,closedAt:x.closedAt,daysToResolution:x.daysToResolution,createdAt:x.createdAt,updatedAt:x.updatedAt};}
function aggregate(){const d=db();const outcomes=(d.caseOutcomes||[]).filter(x=>x.status!=='Voided');const confirmed=outcomes.filter(x=>x.clientConfirmed);const sum=k=>money(confirmed.reduce((s,x)=>s+Number(x[k]||0),0));const times=confirmed.map(x=>Number(x.daysToResolution)).filter(Number.isFinite);return{totalOutcomes:outcomes.length,confirmedOutcomes:confirmed.length,totalValueSaved:sum('valueSaved'),debtReduced:sum('debtReduced'),assetValueProtected:sum('assetValueProtected'),taxExposureReduced:sum('taxExposureReduced'),cashFlowImprovement:sum('cashFlowImprovement'),jobsProtected:Math.round(confirmed.reduce((s,x)=>s+Number(x.jobsProtected||0),0)),averageDaysToResolution:times.length?Math.round((times.reduce((a,b)=>a+b,0)/times.length)*10)/10:0};}

module.exports=function registerOutcomeRoutes(app){
  function resolve(req,id){const d=db();const item=(d.rescueCases||[]).find(c=>c.id===id);if(!item)return null;if(req.session?.admin)return item;if(req.session?.professionalId&&item.assignedProfessionalId===req.session.professionalId)return item;if(req.session?.rescueCaseId===item.id)return item;return null;}
  app.get('/api/case-room/:id/outcome',(req,res)=>{const item=resolve(req,req.params.id);if(!item)return res.status(403).json({error:'Case outcome access denied.'});const outcome=(db().caseOutcomes||[]).find(x=>x.caseId===item.id&&x.status!=='Voided');res.json({caseId:item.id,caseNumber:item.caseNumber,outcome:outcomePublic(outcome)});});
  app.post('/api/case-room/:id/outcome',(req,res)=>{const item=resolve(req,req.params.id);if(!item)return res.status(403).json({error:'Case outcome access denied.'});if(!req.session?.professionalId&&!req.session?.admin)return res.status(403).json({error:'Only the assigned professional or administrator can record a case outcome.'});const existing=(db().caseOutcomes||[]).find(x=>x.caseId===item.id&&x.status!=='Voided');if(existing)return res.status(409).json({error:'An active outcome record already exists for this case.'});const outcomeType=normalise(req.body.outcomeType).slice(0,120);const resolutionSummary=normalise(req.body.resolutionSummary).slice(0,2200);if(!outcomeType||!resolutionSummary)return res.status(400).json({error:'Outcome type and resolution summary are required.'});const amountBefore=money(req.body.amountBefore||item.amount||0),amountAfter=money(req.body.amountAfter||0);const closedAt=new Date().toISOString();const record=store.insert('caseOutcomes',{caseId:item.id,caseNumber:item.caseNumber,professionalId:item.assignedProfessionalId||null,outcomeType,resolutionSummary,amountBefore,amountAfter,valueSaved:money(req.body.valueSaved||Math.max(0,amountBefore-amountAfter)),debtReduced:money(req.body.debtReduced),assetValueProtected:money(req.body.assetValueProtected),taxExposureReduced:money(req.body.taxExposureReduced),cashFlowImprovement:money(req.body.cashFlowImprovement),jobsProtected:Math.max(0,Math.round(Number(req.body.jobsProtected||0))),clientConfirmed:false,clientConfirmedAt:null,status:'Awaiting client confirmation',closedAt,daysToResolution:daysBetween(item.createdAt,closedAt)});store.update('rescueCases',item.id,{status:'Resolved',resolvedAt:closedAt,outcomeId:record.id});store.insert('caseActivity',{caseId:item.id,actorRole:req.session?.admin?'Admin':'Professional',actorName:req.session?.admin?'The Chancellor Command Centre':(item.assignedProfessional||'Professional'),action:'Case outcome recorded',detail:`${outcomeType} · value saved R${Number(record.valueSaved||0).toFixed(2)}`});res.status(201).json({outcome:outcomePublic(record)});});
  app.patch('/api/case-room/:id/outcome/:outcomeId',(req,res)=>{const item=resolve(req,req.params.id);if(!item)return res.status(403).json({error:'Case outcome access denied.'});if(!req.session?.professionalId&&!req.session?.admin)return res.status(403).json({error:'Only the assigned professional or administrator can update a case outcome.'});const current=(db().caseOutcomes||[]).find(x=>x.id===req.params.outcomeId&&x.caseId===item.id&&x.status!=='Voided');if(!current)return res.status(404).json({error:'Outcome record not found.'});if(current.clientConfirmed)return res.status(409).json({error:'Client-confirmed outcomes are locked. Create an administrator correction note instead of rewriting history.'});const patch={};['outcomeType','resolutionSummary'].forEach(k=>{if(req.body[k]!==undefined)patch[k]=normalise(req.body[k]).slice(0,k==='resolutionSummary'?2200:120)});['amountBefore','amountAfter','valueSaved','debtReduced','assetValueProtected','taxExposureReduced','cashFlowImprovement'].forEach(k=>{if(req.body[k]!==undefined)patch[k]=money(req.body[k])});if(req.body.jobsProtected!==undefined)patch.jobsProtected=Math.max(0,Math.round(Number(req.body.jobsProtected||0)));const updated=store.update('caseOutcomes',current.id,patch);res.json({outcome:outcomePublic(updated)});});
  app.post('/api/rescue/case-outcome/confirm',(req,res)=>{if(!req.session?.rescueCaseId)return res.status(401).json({error:'Rescue case sign-in required.'});const item=(db().rescueCases||[]).find(c=>c.id===req.session.rescueCaseId);if(!item)return res.status(404).json({error:'Rescue case not found.'});const outcome=(db().caseOutcomes||[]).find(x=>x.caseId===item.id&&x.status!=='Voided');if(!outcome)return res.status(404).json({error:'No outcome is awaiting confirmation.'});if(outcome.clientConfirmed)return res.json({outcome:outcomePublic(outcome)});const confirmed=String(req.body.confirm||'').toLowerCase()==='yes'||req.body.confirm===true;if(!confirmed)return res.status(400).json({error:'Confirm that the recorded outcome reflects the case result.'});const updated=store.update('caseOutcomes',outcome.id,{clientConfirmed:true,clientConfirmedAt:new Date().toISOString(),status:'Confirmed'});store.insert('caseActivity',{caseId:item.id,actorRole:'Client',actorName:item.name||'Client',action:'Case outcome confirmed',detail:updated.outcomeType});res.json({outcome:outcomePublic(updated)});});
  app.get('/api/admin/outcomes',(req,res)=>{if(!req.session?.admin)return res.status(401).json({error:'Administrator sign-in required.'});const d=db();const outcomes=(d.caseOutcomes||[]).filter(x=>x.status!=='Voided').map(x=>{const c=(d.rescueCases||[]).find(z=>z.id===x.caseId)||{};return{...outcomePublic(x),clientName:c.name||'',professionalName:c.assignedProfessional||'',caseType:c.type||''};}).sort((a,b)=>new Date(b.closedAt)-new Date(a.closedAt));res.json({metrics:aggregate(),outcomes});});
};

module.exports.aggregateOutcomes=aggregate;
