const $=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const code=sessionStorage.getItem('newAccessCode'); if(code) $('#newCode').innerHTML=`Your new access code is <strong>${esc(code)}</strong>. Save it before signing in.`;
const qs=new URLSearchParams(location.search);
function paymentComplete(payments=[]){return payments.some(p=>String(p.status||'').toUpperCase()==='COMPLETE')}
async function load(){ const r=await fetch('/api/portal'); if(!r.ok)return; const d=await r.json(); $('#login').classList.add('hidden'); $('#dashboard').classList.remove('hidden'); $('#businessName').textContent=d.audit.businessName; $('#clientGoal').textContent=d.audit.goal; $('#score').textContent=d.audit.score; $('#band').textContent=d.audit.band; $('#status').textContent=d.audit.status; $('#recommendation').textContent=d.audit.recommendation; $('#fileCount').textContent=d.files.length; $('#files').innerHTML=d.files.length?d.files.map(f=>`<div class="file-row"><span>${esc(f.originalName)}<small> · ${(f.size/1024).toFixed(0)} KB</small></span><span class="badge">${esc(f.status)}</span></div>`).join(''):'<p>No documents uploaded yet.</p>'; const paid=paymentComplete(d.payments); const pay=$('#payButton'),payStatus=$('#payStatus'),next=$('#nextStep'); if(paid){pay.disabled=true;pay.textContent='Payment received ✓';payStatus.textContent='Your R500 audit payment is confirmed. Your Growth Desk can now proceed with review.';payStatus.className='status';next.textContent=d.files.length?'Human review':'Upload documents'}else{pay.disabled=false;pay.textContent='Pay R500 & start my review';next.textContent='Secure payment';if(qs.get('payment')==='returned')payStatus.textContent='You have returned from PayFast. We are waiting for payment confirmation; this page will update automatically.';if(qs.get('payment')==='cancelled'){payStatus.textContent='Payment was not completed. You can try again when ready.';payStatus.className='status error'}} }
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#loginStatus');st.textContent='Signing in…';const r=await fetch('/api/auth/client',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const d=await r.json();if(!r.ok){st.textContent=d.error;st.className='status error';return}sessionStorage.removeItem('newAccessCode');load()});
$('#uploadForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#uploadStatus'),button=e.currentTarget.querySelector('button');st.textContent='Uploading securely…';button.disabled=true;const r=await fetch('/api/uploads',{method:'POST',body:new FormData(e.currentTarget)});const d=await r.json();button.disabled=false;if(!r.ok){st.textContent=d.error;st.className='status error';return}st.textContent='Documents received. Your Growth Desk now has them for review.';st.className='status';e.currentTarget.reset();load()});
$('#payButton').addEventListener('click',async()=>{const st=$('#payStatus'),button=$('#payButton');st.className='status';st.textContent='Preparing secure PayFast checkout…';button.disabled=true;const r=await fetch('/api/payfast/checkout',{method:'POST'});const d=await r.json();if(!r.ok){st.textContent=d.error||'Secure checkout is not available yet.';st.className='status error';button.disabled=false;return}const f=$('#payForm');f.action=d.url;f.innerHTML=Object.entries(d.fields).map(([k,v])=>`<input type="hidden" name="${esc(k)}" value="${esc(v)}">`).join('');f.submit()});
$('#logout').addEventListener('click',async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()}); load();
if(qs.get('payment')==='returned')setTimeout(load,4000);
