(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!q('link[data-production-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='production.css?v=20260811-1';l.dataset.productionStyles='1';document.head.appendChild(l)}
let loading=false;
function ensurePanel(){const view=q('#growthView');if(!view||q('#productionPanel'))return;view.insertAdjacentHTML('beforeend','<section class="panel" id="productionPanel"><div class="panel-heading"><div><p class="eyebrow">Automatic production engine</p><h2>Brief → AI draft → Human review → Revision → Release</h2><p class="muted">AI accelerates drafting. A Growth Desk reviewer remains responsible for factual accuracy, scope, revisions and final release.</p></div><span class="badge" id="productionAiBadge">AI CHECK</span></div><div class="metric-grid"><div class="metric"><small>Production workspaces</small><strong id="prTotal">0</strong></div><div class="metric"><small>Briefing</small><strong id="prBriefing">0</strong></div><div class="metric"><small>Human review</small><strong id="prReview">0</strong></div><div class="metric"><small>Finalised</small><strong id="prFinalised">0</strong></div></div><div id="productionList" class="production-list"><p class="muted">No production workspaces yet.</p></div></section>')}
function latest(p){return (p.versions||[]).find(v=>v.id===p.currentVersionId)||(p.versions||[]).slice(-1)[0]||null}
function feedbackList(items=[]){return items.length?items.slice().reverse().map(f=>`<div class="production-feedback"><b>Client feedback</b><p>${esc(f.text)}</p><small>${new Date(f.createdAt).toLocaleString('en-ZA')}</small></div>`).join(''):'<p class="muted">No client feedback yet.</p>'}
function card(row){const a=row.assignment,p=row.production,v=latest(p);return `<article class="production-card" data-id="${esc(a.id)}"><div class="production-head"><div><p class="eyebrow">${esc(row.audit.businessName||'Client')}</p><h3>${esc(a.service)}</h3><p>${esc(row.audit.name)} · ${esc(row.audit.email)}</p><p><b>Goal:</b> ${esc(row.audit.goal||'')}</p></div><div><span class="badge">${esc(p.status)}</span><small>${(p.versions||[]).length} version${(p.versions||[]).length===1?'':'s'}</small></div></div><div class="production-grid"><label class="wide">Verified production brief / facts<textarea class="production-brief" rows="4" placeholder="Add verified facts, figures, context and instructions. Do not rely on the AI to infer missing facts.">${esc(p.brief||'')}</textarea></label><label class="wide">Human review notes<textarea class="production-review-notes" rows="3" placeholder="Internal reviewer notes">${esc(p.reviewNotes||'')}</textarea></label><div class="wide source-meta"><b>Uploaded source files available to the human reviewer</b><p>${row.sourceFiles.length?row.sourceFiles.map(esc).join(' · '):'None listed yet.'}</p></div><div class="wide production-actions"><button class="button compact save-brief">Save brief</button><button class="button compact generate-draft">Generate AI first draft</button></div><label class="wide">Current working draft<textarea class="production-draft" rows="18" placeholder="The draft will appear here. You can edit it directly before saving.">${esc(v?.text||'')}</textarea></label><div class="wide production-actions"><button class="button compact save-draft">Save human edit</button><button class="button compact dark finalise-draft">Finalise & release branded document</button></div><label class="wide">AI revision instruction<textarea class="revision-instruction" rows="3" placeholder="Example: tighten the executive summary, keep all verified figures unchanged, and strengthen the implementation plan."></textarea></label><button class="button compact revise-draft">Revise with AI</button><p class="status production-status"></p><details class="wide"><summary>Version history & client feedback</summary><div class="production-history">${(p.versions||[]).slice().reverse().map(x=>`<div class="file-row"><span><b>v${x.number}</b> · ${esc(x.kind)}<small> · ${esc(x.author)} · ${new Date(x.createdAt).toLocaleString('en-ZA')}</small></span></div>`).join('')||'<p class="muted">No versions yet.</p>'}${feedbackList(row.feedback)}</div></details></div></article>`}
async function call(card,url,options,label){const st=card.querySelector('.production-status');st.className='status';st.textContent=label;const r=await fetch(url,options);let j={};try{j=await r.json()}catch{}if(!r.ok){st.textContent=j.error||'The production action could not be completed.';st.className='status error';throw new Error(st.textContent)}return j}
async function load(){ensurePanel();const box=q('#productionList');if(!box||loading)return;loading=true;try{const r=await fetch('/api/admin/production');if(r.status===401)return;if(!r.ok)throw new Error();const d=await r.json(),m=d.metrics||{};q('#prTotal').textContent=m.total||0;q('#prBriefing').textContent=m.briefing||0;q('#prReview').textContent=m.review||0;q('#prFinalised').textContent=m.finalised||0;q('#productionAiBadge').textContent=d.aiConfigured?'AI DRAFTING READY':'MANUAL DRAFTING';box.innerHTML=(d.rows||[]).length?d.rows.map(card).join(''):'<p class="muted">No paid assignments are ready for production yet.</p>';qa('.production-card').forEach(c=>{
  const id=c.dataset.id,brief=()=>c.querySelector('.production-brief').value,reviewNotes=()=>c.querySelector('.production-review-notes').value,draft=()=>c.querySelector('.production-draft').value;
  c.querySelector('.save-brief').onclick=async()=>{try{await call(c,`/api/admin/production/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({brief:brief(),reviewNotes:reviewNotes()})},'Saving brief…');c.querySelector('.production-status').textContent='Brief saved.'}catch{}};
  c.querySelector('.generate-draft').onclick=async e=>{e.currentTarget.disabled=true;try{const j=await call(c,`/api/admin/production/${id}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brief:brief()})},'Generating first draft…');c.querySelector('.production-draft').value=j.version?.text||'';c.querySelector('.production-status').textContent='AI first draft created. Human review is required before release.';setTimeout(load,500)}catch{}finally{e.currentTarget.disabled=false}};
  c.querySelector('.save-draft').onclick=async()=>{try{const j=await call(c,`/api/admin/production/${id}/save`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:draft(),reviewNotes:reviewNotes()})},'Saving reviewed draft…');c.querySelector('.production-draft').value=j.version?.text||draft();c.querySelector('.production-status').textContent='Human-edited version saved.';setTimeout(load,400)}catch{}};
  c.querySelector('.revise-draft').onclick=async e=>{const instruction=c.querySelector('.revision-instruction').value;if(!instruction.trim()){c.querySelector('.production-status').textContent='Enter revision instructions first.';c.querySelector('.production-status').className='status error';return}e.currentTarget.disabled=true;try{const j=await call(c,`/api/admin/production/${id}/revise`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instruction})},'The Chancellor is revising the draft…');c.querySelector('.production-draft').value=j.version?.text||'';c.querySelector('.production-status').textContent='AI revision created. Review it carefully before release.';setTimeout(load,500)}catch{}finally{e.currentTarget.disabled=false}};
  c.querySelector('.finalise-draft').onclick=async e=>{if(!confirm('Release the current reviewed version to the client portal as the branded final document?'))return;e.currentTarget.disabled=true;try{await call(c,`/api/admin/production/${id}/finalise`,{method:'POST'},'Creating branded final document…');c.querySelector('.production-status').textContent='Final branded document released to the client portal.';setTimeout(load,600)}catch{}finally{e.currentTarget.disabled=false}};
})}catch{box.innerHTML='<p class="status error">Production workspaces could not be loaded.</p>'}finally{loading=false}}
ensurePanel();const dash=q('#adminDash');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(load,350)}).observe(dash,{attributes:true,attributeFilter:['class']});qa('.command-tabs button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='growthView')setTimeout(load,120)}));setTimeout(()=>{if(dash&&!dash.classList.contains('hidden'))load()},1100);
})();
