(()=>{
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!q('link[data-production-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='production.css?v=20260811-1';l.dataset.productionStyles='1';document.head.appendChild(l)}
function ensurePanel(){const dashboard=q('#dashboard');if(!dashboard||q('#clientProductionPanel'))return;const logout=q('#logout');const section=document.createElement('section');section.className='panel';section.id='clientProductionPanel';section.innerHTML='<p class="eyebrow">Step 5 · Paid work</p><h2>Your production workspace</h2><p>Your paid Growth Desk assignments appear here as they move through drafting, human review and final delivery.</p><div id="clientProduction"><p class="muted">No paid production assignment yet.</p></div><p id="clientProductionStatus" class="status"></p>';dashboard.insertBefore(section,logout)}
async function load(){ensurePanel();const box=q('#clientProduction');if(!box)return;const [pr,ar]=await Promise.all([fetch('/api/client/production'),fetch('/api/client/assignments')]);if(!pr.ok||!ar.ok)return;const pd=await pr.json(),ad=await ar.json();const assignments=ad.assignments||[];if(!pd.rows?.length){box.innerHTML='<p class="muted">Once a follow-on service is paid, its production status and final files will appear here.</p>';return}box.innerHTML=pd.rows.map(row=>{const a=assignments.find(x=>x.id===row.assignmentId)||{};const files=a.files||[];const feedback=row.feedback||[];return `<article class="production-client-card" data-id="${esc(row.assignmentId)}"><div class="production-client-head"><div><h3>${esc(row.service)}</h3><p>${esc(a.clientMessage||'Your assignment is being prepared by the Growth Desk.')}</p></div><span class="badge">${esc(row.status)}</span></div><div class="progress-track"><i style="width:${Math.max(0,Math.min(100,Number(a.progress||0)))}%"></i></div><small>${Number(a.progress||0)}% complete${a.deadline?` · Target ${new Date(a.deadline).toLocaleDateString('en-ZA')}`:''}</small><div class="production-files">${files.length?files.map(f=>`<div class="delivery-file"><span>${esc(f.originalName)}<small> · ${esc(f.status||'Available')}</small></span><a class="button compact" href="/api/client/deliverables/${encodeURIComponent(f.id)}/download">Download</a></div>`).join(''):'<p class="muted">No final file has been released yet.</p>'}</div>${row.status==='Finalised'||a.status==='Client review'?`<label>Send final feedback<textarea class="client-feedback" rows="3" placeholder="Tell the Growth Desk exactly what should be corrected or confirmed."></textarea></label><button class="button compact send-feedback">Send feedback</button>`:''}${feedback.length?`<details><summary>Your feedback history</summary>${feedback.slice().reverse().map(f=>`<p>${esc(f.text)}<small> · ${new Date(f.createdAt).toLocaleString('en-ZA')}</small></p>`).join('')}</details>`:''}</article>`}).join('');
box.querySelectorAll('.send-feedback').forEach(btn=>btn.onclick=async()=>{const card=btn.closest('.production-client-card'),text=card.querySelector('.client-feedback').value,st=q('#clientProductionStatus');if(!text.trim()){st.textContent='Please enter your feedback first.';st.className='status error';return}btn.disabled=true;st.textContent='Sending feedback…';st.className='status';const r=await fetch(`/api/client/assignments/${card.dataset.id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const j=await r.json();btn.disabled=false;if(!r.ok){st.textContent=j.error||'Feedback could not be sent.';st.className='status error';return}st.textContent='Feedback received by the Growth Desk.';card.querySelector('.client-feedback').value='';setTimeout(load,500)})}
ensurePanel();const dash=q('#dashboard');if(dash)new MutationObserver(()=>{if(!dash.classList.contains('hidden'))setTimeout(load,250)}).observe(dash,{attributes:true,attributeFilter:['class']});setTimeout(()=>{if(dash&&!dash.classList.contains('hidden'))load()},800);
if(!document.querySelector('script[data-client-followups]')){const s=document.createElement('script');s.src='followup-client.js?v=20260811-1';s.dataset.clientFollowups='1';document.body.appendChild(s)}
})();
