const crypto=require('node:crypto');
const store=require('./store');
const {normalise,hashSecret,verifySecret,accessCode}=require('./core');
const db=()=>store.read();
const money=n=>Math.max(0,Math.round(Number(n||0)*100)/100);
const code=()=>`CH-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
const requireAdmin=(req,res,next)=>req.session?.admin?next():res.status(401).json({error:'Administrator sign-in required.'});
const safePartner=p=>({id:p.id,partnerNumber:p.partnerNumber,name:p.name,organisation:p.organisation,partnerType:p.partnerType,email:p.email,phone:p.phone,referralCode:p.referralCode,status:p.status,commissionEnabled:Boolean(p.commissionEnabled),auditCommissionRate:Number(p.auditCommissionRate||0),caseCommissionRate:Number(p.caseCommissionRate||0),createdAt:p.createdAt,updatedAt:p.updatedAt});
function paidForLead(lead,d){if(lead.leadType==='Growth Desk Audit')return(d.payments||[]).filter(p=>p.auditId===lead.leadId&&String(p.status).toUpperCase()==='COMPLETE').reduce((s,p)=>s+Number(p.amount||0),0);return(d.casePayments||[]).filter(p=>p.caseId===lead.leadId&&String(p.status).toUpperCase()==='COMPLETE').reduce((s,p)=>s+Number(p.amount||0),0)}
function commissionFor(lead,partner,d){if(!partner?.commissionEnabled)return 0;const paid=paidForLead(lead,d);const rate=lead.leadType==='Growth Desk Audit'?Number(partner.auditCommissionRate||0):Number(partner.caseCommissionRate||0);return money(paid*Math.max(0,Math.min(.5,rate)))}
function partnerStats(partnerId){const d=db(),partner=(d.referralPartners||[]).find(p=>p.id===partnerId);if(!partner)return null;const leads=(d.referralLeads||[]).filter(l=>l.partnerId===partnerId);const rows=leads.map(l=>({...l,paidAmount:money(paidForLead(l,d)),commissionEarned:commissionFor(l,partner,d)}));const converted=rows.filter(r=>r.paidAmount>0);const earned=money(rows.reduce((s,r)=>s+r.commissionEarned,0));const payouts=(d.referralPayouts||[]).filter(p=>p.partnerId===partnerId);const paidOut=money(payouts.filter(p=>p.status==='Paid out').reduce((s,p)=>s+Number(p.amount||0),0));return{partner:safePartner(partner),metrics:{leads:rows.length,converted:converted.length,conversionRate:rows.length?Math.round(converted.length/rows.length*1000)/10:0,referredRevenue:money(rows.reduce((s,r)=>s+r.paidAmount,0)),commissionEarned:earned,commissionOutstanding:money(earned-paidOut),paidOut},leads:rows,payouts};}
module.exports=function registerReferralRoutes(app){
  app.post('/api/referrals/capture',(req,res)=>{const referralCode=normalise(req.body.referralCode).toUpperCase().slice(0,40);const partner=(db().referralPartners||[]).find(p=>String(p.referralCode||'').toUpperCase()===referralCode&&p.status==='Active');if(!partner){delete req.session.referralPartnerId;delete req.session.referralCode;return res.json({captured:false});}req.session.referralPartnerId=partner.id;req.session.referralCode=partner.referralCode;res.json({captured:true,referralCode:partner.referralCode});});
  app.post('/api/referrals/link',(req,res)=>{const partnerId=req.session?.referralPartnerId;if(!partnerId)return res.json({linked:false});const leadType=normalise(req.body.leadType);let leadId=null,leadLabel='';if(leadType==='Growth Desk Audit'&&req.session?.clientId){leadId=req.session.clientId;const a=(db().audits||[]).find(x=>x.id===leadId);leadLabel=a?.businessName||a?.name||'Growth Desk lead';}else if(leadType==='Rescue Case'&&req.session?.rescueCaseId){leadId=req.session.rescueCaseId;const c=(db().rescueCases||[]).find(x=>x.id===leadId);leadLabel=c?.caseNumber||'Rescue case';}else return res.status(400).json({error:'No eligible signed-in lead is available to link.'});const exists=(db().referralLeads||[]).find(l=>l.leadType===leadType&&l.leadId===leadId);if(exists)return res.json({linked:true,lead:exists});const partner=(db().referralPartners||[]).find(p=>p.id===partnerId&&p.status==='Active');if(!partner)return res.json({linked:false});const lead=store.insert('referralLeads',{partnerId:partner.id,referralCode:partner.referralCode,leadType,leadId,leadLabel,status:'Referred'});res.status(201).json({linked:true,lead});});
  app.post('/api/referrals/partners/apply',(req,res)=>{const required=['name','email','phone','partnerType'];if(required.some(k=>!normalise(req.body[k])))return res.status(400).json({error:'Complete the required partner details.'});const access=accessCode(),partner=store.insert('referralPartners',{partnerNumber:`RP-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,name:normalise(req.body.name).slice(0,120),organisation:normalise(req.body.organisation).slice(0,180),partnerType:normalise(req.body.partnerType).slice(0,120),email:normalise(req.body.email).toLowerCase().slice(0,180),phone:normalise(req.body.phone).slice(0,60),referralCode:code(),status:'Pending approval',commissionEnabled:false,auditCommissionRate:0,caseCommissionRate:0,accessHash:hashSecret(access)});req.session.referralPartnerPortalId=partner.id;res.status(201).json({partner:safePartner(partner),accessCode:access,message:'Partner application received. Save this access code.'});});
  app.post('/api/referrals/partners/access',(req,res)=>{const email=normalise(req.body.email).toLowerCase(),access=normalise(req.body.code);const partner=[...(db().referralPartners||[])].reverse().find(p=>p.email===email&&p.accessHash&&verifySecret(access,p.accessHash));if(!partner)return res.status(401).json({error:'Email or partner access code is incorrect.'});req.session.referralPartnerPortalId=partner.id;res.json({ok:true,partner:safePartner(partner)});});
  app.post('/api/referrals/partners/logout',(req,res)=>{delete req.session.referralPartnerPortalId;res.json({ok:true});});
  app.get('/api/referrals/partner-portal',(req,res)=>{const id=req.session?.referralPartnerPortalId;if(!id)return res.status(401).json({error:'Partner sign-in required.'});const stats=partnerStats(id);if(!stats)return res.status(404).json({error:'Partner record not found.'});res.json(stats);});
  app.get('/api/admin/referrals',requireAdmin,(_req,res)=>{const d=db();const partners=(d.referralPartners||[]).map(p=>partnerStats(p.id));const totals=partners.reduce((a,p)=>{a.partners++;a.leads+=p.metrics.leads;a.converted+=p.metrics.converted;a.referredRevenue+=p.metrics.referredRevenue;a.commissionOutstanding+=p.metrics.commissionOutstanding;return a},{partners:0,leads:0,converted:0,referredRevenue:0,commissionOutstanding:0});totals.referredRevenue=money(totals.referredRevenue);totals.commissionOutstanding=money(totals.commissionOutstanding);res.json({metrics:totals,partners,payouts:d.referralPayouts||[]});});
  app.patch('/api/admin/referrals/partners/:id',requireAdmin,(req,res)=>{const current=(db().referralPartners||[]).find(p=>p.id===req.params.id);if(!current)return res.status(404).json({error:'Referral partner not found.'});const patch={};if(req.body.status!==undefined){const status=normalise(req.body.status);if(!['Pending approval','Active','Suspended','Declined'].includes(status))return res.status(400).json({error:'Choose a valid partner status.'});patch.status=status}if(req.body.commissionEnabled!==undefined)patch.commissionEnabled=Boolean(req.body.commissionEnabled);for(const k of['auditCommissionRate','caseCommissionRate'])if(req.body[k]!==undefined){const rate=Number(req.body[k]);if(!Number.isFinite(rate)||rate<0||rate>.5)return res.status(400).json({error:'Commission rate must be between 0 and 0.50.'});patch[k]=rate}const partner=store.update('referralPartners',current.id,patch);res.json({partner:safePartner(partner),stats:partnerStats(partner.id)});});
  app.post('/api/admin/referrals/partners/:id/payouts',requireAdmin,(req,res)=>{const stats=partnerStats(req.params.id);if(!stats)return res.status(404).json({error:'Referral partner not found.'});const amount=money(req.body.amount||stats.metrics.commissionOutstanding);if(amount<=0||amount>stats.metrics.commissionOutstanding+0.01)return res.status(400).json({error:'Enter an amount within the outstanding commission balance.'});const payout=store.insert('referralPayouts',{partnerId:req.params.id,amount,status:'Approved for payout',reference:'',note:normalise(req.body.note).slice(0,500)});res.status(201).json({payout});});
  app.patch('/api/admin/referrals/payouts/:id',requireAdmin,(req,res)=>{const p=(db().referralPayouts||[]).find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Referral payout not found.'});const status=normalise(req.body.status);if(!['Approved for payout','Paid out','On hold'].includes(status))return res.status(400).json({error:'Choose a valid payout status.'});const reference=normalise(req.body.reference).slice(0,180);if(status==='Paid out'&&!reference)return res.status(400).json({error:'A payment reference is required before marking a referral payout as paid.'});const payout=store.update('referralPayouts',p.id,{status,reference,paidOutAt:status==='Paid out'?new Date().toISOString():p.paidOutAt||null});res.json({payout});});
};
