const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const multer = require('multer');
const { scoreRescueTriage } = require('./rescue-triage');
const { professionalStats } = require('./reputation-routes');

module.exports = function registerRescueRoutes(app, { store, normalise, hashSecret, verifySecret, accessCode }) {
  const safeCase = item => ({ id:item.id, caseNumber:item.caseNumber, type:item.type, name:item.name, email:item.email, phone:item.phone, country:item.country, problem:item.problem, amount:item.amount, income:item.income, expenses:item.expenses, days:item.days, flags:item.flags, triage:item.triage, status:item.status, assignedProfessional:item.assignedProfessional || null, assignedProfessionalId:item.assignedProfessionalId || null, professionalResponse:item.professionalResponse || null, match:item.match || null, createdAt:item.createdAt, updatedAt:item.updatedAt });
  const safeProfessional = p => ({ id:p.id, applicationNumber:p.applicationNumber, name:p.name, email:p.email, phone:p.phone, profession:p.profession, regulator:p.regulator, registrationNumber:p.registrationNumber, country:p.country, regions:p.regions, languages:p.languages, availability:p.availability, rescueTypes:p.rescueTypes, specialities:p.specialities, verificationStatus:p.verificationStatus, membershipStatus:p.membershipStatus, membershipTier:p.membershipTier, credentialReviewStatus:p.credentialReviewStatus, active:Boolean(p.active), verifiedAt:p.verifiedAt, membershipActivatedAt:p.membershipActivatedAt, subscriptionStatus:p.subscriptionStatus || 'Not configured', subscriptionRenewsAt:p.subscriptionRenewsAt || null, createdAt:p.createdAt, updatedAt:p.updatedAt });
  const categoryTerms = { tax:['tax','sars','revenue','accountant','tax practitioner','vat','paye'], debt:['debt','debt counsellor','ncr','credit','collections','restructuring'], asset:['debt','consumer','credit','repossession','vehicle','mortgage','property','attorney','legal'], business:['business rescue','turnaround','accountant','insolvency','restructuring','cash flow','commercial'], legal:['attorney','legal','litigation','consumer','credit','court','commercial'] };
  const subscriptionCurrent = p => {
    if (p.subscriptionOverride === true) return true;
    if (String(p.subscriptionStatus || '').toLowerCase() !== 'active') return false;
    if (!p.subscriptionRenewsAt) return true;
    const renews = new Date(p.subscriptionRenewsAt).getTime();
    return Number.isFinite(renews) && renews >= Date.now();
  };
  const eligibleProfessional = p => Boolean(p && p.active && String(p.verificationStatus || '').toLowerCase() === 'verified' && String(p.membershipStatus || '').toLowerCase() === 'active member' && subscriptionCurrent(p) && !String(p.availability || '').toLowerCase().includes('not taking'));
  const rankMatches = (caseItem, db) => {
    const active = (db.professionals || []).filter(eligibleProfessional);
    const workloads = {}; (db.rescueCases || []).forEach(c => { if (c.assignedProfessionalId && !['Resolved','Closed'].includes(c.status)) workloads[c.assignedProfessionalId] = (workloads[c.assignedProfessionalId] || 0) + 1; });
    const terms = categoryTerms[caseItem.type] || [];
    return active.map(p => {
      const hay = `${p.profession || ''} ${p.specialities || ''} ${p.rescueTypes || ''}`.toLowerCase(); let score = 0; const reasons = [];
      const hits = terms.filter(t => hay.includes(t)); if (hits.length) { score += Math.min(50, 20 + hits.length * 10); reasons.push(`Speciality fit: ${hits.slice(0,3).join(', ')}`); }
      const pCountry = String(p.country || 'South Africa').toLowerCase(); const cCountry = String(caseItem.country || '').toLowerCase(); if (pCountry && cCountry && (pCountry === cCountry || pCountry.includes('international'))) { score += 18; reasons.push('Jurisdiction fit'); }
      const regions = String(p.regions || p.specialities || '').toLowerCase(); if (cCountry === 'south africa' && (regions.includes('south africa') || pCountry === 'south africa')) { score += 8; reasons.push('South Africa coverage'); }
      const availability = String(p.availability || 'Available').toLowerCase(); if (availability.includes('available') || availability.includes('open')) { score += 8; reasons.push('Available for cases'); }
      const load = workloads[p.id] || 0; score += Math.max(0, 12 - load * 4); reasons.push(`${load} active case${load === 1 ? '' : 's'}`);
      const performance = professionalStats(p.id); const performanceDelta = Math.max(-10, Math.min(10, (Number(performance.score || 70) - 70) / 3)); score += performanceDelta; reasons.push(`Performance ${Number(performance.score || 0).toFixed(0)}/100`);
      return { id:p.id, name:p.name, profession:p.profession, regulator:p.regulator, registrationNumber:p.registrationNumber, country:p.country || 'South Africa', regions:p.regions || '', availability:p.availability || 'Available', workload:load, performanceScore:performance.score, score:Math.max(0,Math.min(100,Math.round(score))), reasons };
    }).filter(x => x.score >= 25).sort((a,b) => b.score - a.score || a.workload - b.workload).slice(0,5);
  };

  const credentialDir = path.join(process.env.DATA_DIR || path.join(__dirname, 'data'), 'professional-credentials');
  fs.mkdirSync(credentialDir, { recursive:true });
  const credentialTypes = (process.env.ALLOWED_UPLOAD_TYPES || 'application/pdf,image/jpeg,image/png').split(',');
  const credentialUpload = multer({ storage:multer.diskStorage({ destination:credentialDir, filename:(_req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(8).toString('hex')}${path.extname(file.originalname).toLowerCase()}`) }), limits:{ fileSize:Number(process.env.MAX_UPLOAD_MB || 10)*1024*1024, files:6 }, fileFilter:(_req,file,cb)=>cb(null,credentialTypes.includes(file.mimetype)) });
  const requireProfessional=(req,res,next)=>req.session.professionalId?next():res.status(401).json({error:'Professional Network sign-in required.'});

  app.post('/api/rescue/cases', (req, res) => {
    const required = ['name','email','phone','country','type','problem']; if (required.some(k => !normalise(req.body[k]))) return res.status(400).json({ error:'Please complete the required rescue information.' });
    const validTypes = ['tax','debt','asset','business','legal']; const type = normalise(req.body.type).toLowerCase(); if (!validTypes.includes(type)) return res.status(400).json({ error:'Choose a valid rescue category.' });
    const triage = scoreRescueTriage({ ...req.body, type }); const code = accessCode(); const idPart = crypto.randomBytes(3).toString('hex').toUpperCase();
    const item = store.insert('rescueCases', { caseNumber:`CR-${new Date().getFullYear()}-${idPart}`, type, name:normalise(req.body.name).slice(0,120), email:normalise(req.body.email).toLowerCase().slice(0,180), phone:normalise(req.body.phone).slice(0,60), country:normalise(req.body.country).slice(0,80), problem:normalise(req.body.problem).slice(0,2500), amount:triage.amount, income:triage.income, expenses:triage.expenses, days:triage.days, flags:triage.flags, triage:{score:triage.score,band:triage.band,specialist:triage.specialist,priorities:triage.priorities}, status:'New — awaiting case review', accessHash:hashSecret(code), assignedProfessional:null, assignedProfessionalId:null, professionalResponse:null, match:null });
    req.session.rescueCaseId = item.id; res.status(201).json({ caseNumber:item.caseNumber, accessCode:code, status:item.status, triage:item.triage, message:'Save this access code. It is shown only once.' });
  });
  app.post('/api/rescue/access', (req, res) => { const db = store.read(); const email = normalise(req.body.email).toLowerCase(); const code = normalise(req.body.code); const item = [...(db.rescueCases||[])].reverse().find(x => x.email === email && verifySecret(code, x.accessHash)); if (!item) return res.status(401).json({ error:'Email or rescue access code is incorrect.' }); req.session.rescueCaseId = item.id; res.json({ ok:true, case:safeCase(item) }); });
  app.get('/api/rescue/case', (req, res) => { if (!req.session.rescueCaseId) return res.status(401).json({ error:'Rescue case sign-in required.' }); const item = (store.read().rescueCases||[]).find(x=>x.id===req.session.rescueCaseId); if (!item) return res.status(404).json({ error:'Rescue case not found.' }); res.json({ case:safeCase(item) }); });

  app.post('/api/professionals/apply', (req, res) => { const required=['name','email','phone','profession','registrationNumber','regulator','specialities']; if(required.some(k=>!normalise(req.body[k]))) return res.status(400).json({ error:'Please complete every professional application field.' }); const number=`PRO-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`; const code=accessCode(); const item=store.insert('professionals',{ applicationNumber:number, name:normalise(req.body.name).slice(0,120), email:normalise(req.body.email).toLowerCase().slice(0,180), phone:normalise(req.body.phone).slice(0,60), profession:normalise(req.body.profession).slice(0,140), registrationNumber:normalise(req.body.registrationNumber).slice(0,120), regulator:normalise(req.body.regulator).slice(0,140), country:normalise(req.body.country || 'South Africa').slice(0,80), regions:normalise(req.body.regions).slice(0,500), languages:normalise(req.body.languages).slice(0,300), availability:normalise(req.body.availability || 'Available').slice(0,80), rescueTypes:normalise(req.body.rescueTypes).slice(0,400), specialities:normalise(req.body.specialities).slice(0,1800), verificationStatus:'Pending verification', membershipStatus:'Application received', membershipTier:'Chancellor Verified', subscriptionStatus:'Not configured', active:false, verifiedAt:null, membershipActivatedAt:null, credentialReviewStatus:'Documents outstanding', accessHash:hashSecret(code) }); req.session.professionalApplicationId=item.id; req.session.professionalId=item.id; res.status(201).json({ applicationNumber:number, accessCode:code, status:'Application received', uploadReady:true, portalUrl:'/professional-portal.html', message:'Your application has entered The Chancellor’s Professional Network vetting process. Save your professional access code.' }); });
  app.post('/api/professionals/access',(req,res)=>{const db=store.read();const email=normalise(req.body.email).toLowerCase();const code=normalise(req.body.code);const pro=[...(db.professionals||[])].reverse().find(p=>p.email===email&&p.accessHash&&verifySecret(code,p.accessHash));if(!pro)return res.status(401).json({error:'Email or Professional Network access code is incorrect.'});req.session.professionalId=pro.id;req.session.professionalApplicationId=pro.id;res.json({ok:true,professional:safeProfessional(pro)});});
  app.post('/api/professionals/logout',(req,res)=>{delete req.session.professionalId;delete req.session.professionalApplicationId;res.json({ok:true});});
  app.get('/api/professionals/portal',requireProfessional,(req,res)=>{const db=store.read();const pro=(db.professionals||[]).find(p=>p.id===req.session.professionalId);if(!pro)return res.status(404).json({error:'Professional membership record not found.'});const cases=(db.rescueCases||[]).filter(c=>c.assignedProfessionalId===pro.id).map(safeCase);const credentials=(db.credentialFiles||[]).filter(f=>f.professionalId===pro.id).map(({storedName,...f})=>f);res.json({professional:safeProfessional(pro),cases,credentials,performance:professionalStats(pro.id),metrics:{assigned:cases.length,awaitingResponse:cases.filter(c=>!c.professionalResponse||c.professionalResponse==='Pending').length,inProgress:cases.filter(c=>['Professional assigned','Intervention in progress'].includes(c.status)).length,resolved:cases.filter(c=>c.status==='Resolved').length}});});
  app.patch('/api/professionals/profile',requireProfessional,(req,res)=>{const patch={};if(req.body.availability!==undefined)patch.availability=normalise(req.body.availability).slice(0,80);if(req.body.regions!==undefined)patch.regions=normalise(req.body.regions).slice(0,500);if(req.body.languages!==undefined)patch.languages=normalise(req.body.languages).slice(0,300);const pro=store.update('professionals',req.session.professionalId,patch);res.json({professional:safeProfessional(pro)});});
  app.post('/api/professionals/cases/:id/respond',requireProfessional,(req,res)=>{const db=store.read();const item=(db.rescueCases||[]).find(c=>c.id===req.params.id&&c.assignedProfessionalId===req.session.professionalId);if(!item)return res.status(404).json({error:'Assigned case not found.'});const decision=normalise(req.body.decision);if(!['Accept','Decline'].includes(decision))return res.status(400).json({error:'Choose Accept or Decline.'});if(decision==='Accept'){const updated=store.update('rescueCases',item.id,{professionalResponse:'Accepted',status:'Intervention in progress',professionalRespondedAt:new Date().toISOString()});return res.json({case:safeCase(updated)});}const reason=normalise(req.body.reason).slice(0,500);const previous=[...new Set([...(item.previousProfessionalIds||[]),req.session.professionalId])];const updated=store.update('rescueCases',item.id,{professionalResponse:'Declined',declineReason:reason,previousProfessionalIds:previous,assignedProfessional:null,assignedProfessionalId:null,status:'Professional matching',professionalRespondedAt:new Date().toISOString(),match:null});res.json({case:safeCase(updated)});});

  app.post('/api/professionals/credentials', credentialUpload.array('credentials',6), (req,res)=>{ const professionalId=req.session.professionalId||req.session.professionalApplicationId; if(!professionalId)return res.status(401).json({error:'Start or reopen a Professional Network application before uploading credentials.'}); const pro=(store.read().professionals||[]).find(p=>p.id===professionalId); if(!pro)return res.status(404).json({error:'Professional application not found.'}); if(!req.files?.length)return res.status(400).json({error:'Choose at least one PDF, JPG or PNG credential.'}); const documentType=normalise(req.body.documentType || 'Supporting credential').slice(0,120); const records=req.files.map(file=>store.insert('credentialFiles',{ professionalId:pro.id, applicationNumber:pro.applicationNumber, documentType, originalName:file.originalname.slice(0,240), storedName:file.filename, mime:file.mimetype, size:file.size, reviewStatus:'Pending review', reviewNote:'', reviewedAt:null })); store.update('professionals',pro.id,{credentialReviewStatus:'Credentials received',verificationStatus:'Credentials being checked'}); res.status(201).json({files:records.map(({storedName,...x})=>x),message:'Credentials received securely for vetting.'}); });

  app.get('/api/admin/rescue', (req,res) => { if (!req.session.admin) return res.status(401).json({ error:'Administrator sign-in required.' }); const db=store.read(); const rescueCases=(db.rescueCases||[]).map(item=>({ ...safeCase(item), matchCandidates:rankMatches(item,db) })); const professionals=(db.professionals||[]).map(({accessHash,...x})=>({ ...x, subscriptionCurrent:subscriptionCurrent(x), performance:professionalStats(x.id), credentials:(db.credentialFiles||[]).filter(f=>f.professionalId===x.id).map(({storedName,...f})=>f) })); res.json({ metrics:{ rescueCases:(db.rescueCases||[]).length, critical:(db.rescueCases||[]).filter(x=>Number(x.triage?.score)>=80).length, professionals:(db.professionals||[]).length, verifiedProfessionals:(db.professionals||[]).filter(eligibleProfessional).length }, rescueCases, professionals }); });
  app.get('/api/admin/credentials/:id/download',(req,res)=>{ if(!req.session.admin)return res.status(401).json({error:'Administrator sign-in required.'}); const file=(store.read().credentialFiles||[]).find(f=>f.id===req.params.id); if(!file)return res.status(404).json({error:'Credential not found.'}); const full=path.join(credentialDir,path.basename(file.storedName)); if(!fs.existsSync(full))return res.status(404).json({error:'Credential file is no longer available.'}); res.download(full,file.originalName); });
  app.patch('/api/admin/credentials/:id',(req,res)=>{ if(!req.session.admin)return res.status(401).json({error:'Administrator sign-in required.'}); const patch={}; if(req.body.reviewStatus!==undefined)patch.reviewStatus=normalise(req.body.reviewStatus).slice(0,80); if(req.body.reviewNote!==undefined)patch.reviewNote=normalise(req.body.reviewNote).slice(0,800); patch.reviewedAt=new Date().toISOString(); const file=store.update('credentialFiles',req.params.id,patch); if(!file)return res.status(404).json({error:'Credential not found.'}); const db=store.read(); const creds=(db.credentialFiles||[]).filter(f=>f.professionalId===file.professionalId); const proPatch={credentialReviewStatus:creds.length && creds.every(f=>f.reviewStatus==='Accepted')?'All submitted credentials accepted':creds.some(f=>f.reviewStatus==='Rejected')?'Credential issue requires attention':'Credential review in progress'}; store.update('professionals',file.professionalId,proPatch); res.json({credential:file}); });

  app.post('/api/admin/rescue/:id/auto-match', (req,res) => { if (!req.session.admin) return res.status(401).json({ error:'Administrator sign-in required.' }); const db=store.read(); const item=(db.rescueCases||[]).find(x=>x.id===req.params.id); if(!item)return res.status(404).json({error:'Rescue case not found.'}); const matches=rankMatches(item,db).filter(x=>!(item.previousProfessionalIds||[]).includes(x.id)); if(!matches.length)return res.status(409).json({error:'No verified, paid and available Network member currently matches this case.'}); const best=matches[0]; const assignedAt=new Date().toISOString(); const updated=store.update('rescueCases',item.id,{ assignedProfessional:best.name, assignedProfessionalId:best.id, assignedAt, status:'Professional assigned', professionalResponse:'Pending', match:{score:best.score,reasons:best.reasons,performanceScore:best.performanceScore,matchedAt:assignedAt} }); res.json({case:safeCase(updated),match:best,alternatives:matches.slice(1)}); });
  app.patch('/api/admin/rescue/:id', (req,res) => { if (!req.session.admin) return res.status(401).json({ error:'Administrator sign-in required.' }); const db=store.read(); const current=(db.rescueCases||[]).find(x=>x.id===req.params.id); if(!current)return res.status(404).json({error:'Rescue case not found.'}); const patch={}; if(req.body.status!==undefined)patch.status=normalise(req.body.status).slice(0,200); if(req.body.assignedProfessionalId!==undefined){ if(!req.body.assignedProfessionalId){patch.assignedProfessionalId=null;patch.assignedProfessional='';patch.professionalResponse=null;patch.assignedAt=null;} else {const pro=(db.professionals||[]).find(p=>p.id===req.body.assignedProfessionalId);if(!eligibleProfessional(pro))return res.status(409).json({error:'Manual assignment requires a verified, active, paid and available Network member.'});patch.assignedProfessionalId=pro.id;patch.assignedProfessional=pro.name;patch.professionalResponse='Pending';patch.assignedAt=new Date().toISOString();patch.status='Professional assigned';} } else if(req.body.assignedProfessional!==undefined)patch.assignedProfessional=normalise(req.body.assignedProfessional).slice(0,200); const item=store.update('rescueCases',req.params.id,patch); res.json({case:safeCase(item)}); });
  app.patch('/api/admin/professionals/:id', (req,res) => { if (!req.session.admin) return res.status(401).json({ error:'Administrator sign-in required.' }); const current=(store.read().professionals||[]).find(p=>p.id===req.params.id); if(!current)return res.status(404).json({error:'Professional application not found.'}); const patch={}; if(req.body.verificationStatus!==undefined){ patch.verificationStatus=normalise(req.body.verificationStatus).slice(0,120); if(patch.verificationStatus==='Verified') patch.verifiedAt=new Date().toISOString(); } if(req.body.membershipStatus!==undefined){ patch.membershipStatus=normalise(req.body.membershipStatus).slice(0,120); if(patch.membershipStatus==='Active member') patch.membershipActivatedAt=new Date().toISOString(); } if(req.body.membershipTier!==undefined)patch.membershipTier=normalise(req.body.membershipTier).slice(0,120); if(req.body.subscriptionStatus!==undefined)patch.subscriptionStatus=normalise(req.body.subscriptionStatus).slice(0,120); if(req.body.active!==undefined)patch.active=Boolean(req.body.active); if(req.body.availability!==undefined)patch.availability=normalise(req.body.availability).slice(0,80); if(req.body.subscriptionOverride!==undefined)patch.subscriptionOverride=Boolean(req.body.subscriptionOverride); const final={...current,...patch}; if(final.active && final.verificationStatus!=='Verified') return res.status(400).json({error:'A professional cannot be activated before credentials are verified.'}); if(final.membershipStatus==='Active member' && final.verificationStatus!=='Verified') return res.status(400).json({error:'Membership cannot be activated before verification.'}); if((final.active||final.membershipStatus==='Active member')&&!subscriptionCurrent(final))return res.status(400).json({error:'Active case matching requires a current paid subscription or explicit administrator subscription override.'}); const item=store.update('professionals',req.params.id,patch); res.json({professional:item}); });
};