const assert=require('node:assert/strict');
const {hashSecret,verifySecret,pfEncode,payfastSignature,scoreAudit}=require('../core');
const {scoreReadiness,publicDefinition}=require('../readiness-engine');
const {buildQuoteSuggestion}=require('../quote-engine');
const {scoreRescueTriage}=require('../rescue-triage');

function test(name,fn){try{fn();console.log(`✓ ${name}`)}catch(error){console.error(`✗ ${name}`);throw error}}

test('access secrets verify and reject wrong values',()=>{const stored=hashSecret('ABCD1234');assert.equal(verifySecret('ABCD1234',stored),true);assert.equal(verifySecret('WRONG',stored),false)});
test('PayFast signatures are deterministic and sensitive to amount',()=>{const a=payfastSignature({merchant_id:'10000100',amount:'199.00',item_name:'Membership'},'secret');const b=payfastSignature({merchant_id:'10000100',amount:'199.00',item_name:'Membership'},'secret');const c=payfastSignature({merchant_id:'10000100',amount:'999.00',item_name:'Membership'},'secret');assert.equal(a,b);assert.notEqual(a,c)});
test('PayFast signature encoding matches PHP-style form encoding for special characters',()=>{assert.equal(pfEncode("O'Reilly! * Test~(1)"),'O%27Reilly%21+%2A+Test%7E%281%29');const signature=payfastSignature({merchant_id:'10000100',amount:'199.00',item_name:"O'Reilly! * Test~(1)"},'S!gn~Key*(A)');assert.equal(signature,'1eaf59a8c1b554676edc20d51af8c5a9')});
test('legacy business readiness score caps at 90',()=>{const yes={};for(let i=1;i<=45;i++)yes[`q${String(i).padStart(2,'0')}`]='2';const result=scoreAudit(yes);assert.equal(result.score,90);assert.equal(result.maxScore,90);assert.equal(result.band,'GREEN - Growth ready');assert.equal(result.readinessPercent,100)});
test('legacy business readiness supports partial scoring and priority sections',()=>{const answers={};for(let i=1;i<=45;i++)answers[`q${String(i).padStart(2,'0')}`]='1';for(let i=1;i<=5;i++)answers[`q${String(i).padStart(2,'0')}`]='0';const result=scoreAudit(answers);assert.equal(result.sectionScores['Business Foundation'],0);assert.equal(result.sectionScores['Finance & Cash Flow'],5);assert.equal(result.priorities[0].section,'Business Foundation');assert.equal(result.band,'AMBER - Needs strengthening')});
test('browser supplied legacy readiness totals are ignored',()=>{const result=scoreAudit({score:90,band:'GREEN - Growth ready',q01:'2'});assert.equal(result.score,2);assert.notEqual(result.band,'GREEN - Growth ready')});
test('180-point readiness definition contains 9 sections and 90 questions',()=>{const definition=publicDefinition();assert.equal(definition.length,9);assert.equal(definition.flatMap(s=>s.questions).length,90);assert.equal(definition.reduce((sum,s)=>sum+s.weight,0),180)});
test('180-point readiness engine reaches exactly 180 for fully ready business',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='2';const result=scoreReadiness({answers});assert.equal(result.score,180);assert.equal(result.maxScore,180);assert.equal(result.readinessPercent,100);assert.equal(result.bandCode,'HIGH_PERFORMANCE');assert.equal(result.recommendations.length,3);assert.equal(result.redFlags.length,0)});
test('180-point readiness engine ignores browser supplied score and finds weak priorities',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='2';for(const question of publicDefinition()[5].questions)answers[question.id]='0';const result=scoreReadiness({answers,score:180});assert.equal(result.priorities[0].section,'Finance');assert.ok(result.score<180);assert.ok(result.redFlags.length>0)});
test('multiple critical categories route to R10000 executive recovery',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='2';for(const section of publicDefinition().slice(5,7))for(const question of section.questions)answers[question.id]='0';const result=scoreReadiness({answers});assert.equal(result.priorityIntervention,'30-Day Business Recovery Programme');assert.ok(result.criticalCategories.length>=2);const quote=buildQuoteSuggestion(result);assert.equal(quote.tier,'executive');assert.equal(quote.amount,10000);assert.match(quote.service,/30-Day Business Recovery Programme/)});
test('single Products & Services priority creates R3500 focused implementation',()=>{const quote=buildQuoteSuggestion({recommendations:[{section:'Products & Services',key:'offering',service:'Pricing & Profitability Review',summary:'Improve pricing and margins.'}],priorities:[]});assert.equal(quote.tier,'focused');assert.equal(quote.service,'Pricing & Profitability Review — Focused Implementation');assert.equal(quote.amount,3500);assert.equal(quote.primaryPriority,'Products & Services')});
test('single Customers priority creates R3500 focused implementation',()=>{const quote=buildQuoteSuggestion({recommendations:[{section:'Customers',key:'customers',service:'Customer Growth System',summary:'Improve retention.'}],priorities:[]});assert.equal(quote.tier,'focused');assert.equal(quote.service,'Customer Growth System — Focused Implementation');assert.equal(quote.amount,3500)});
test('two weak areas create R7500 growth implementation',()=>{const quote=buildQuoteSuggestion({readinessPercent:60,sections:{Sales:{percent:50},Marketing:{percent:55},Finance:{percent:80}},recommendations:[{section:'Sales',key:'sales',service:'Sales Growth Intervention',summary:'Improve sales.'}],priorities:[{section:'Sales',key:'sales',percent:50,summary:'Improve sales.'},{section:'Marketing',key:'marketing',percent:55,summary:'Improve marketing.'}]});assert.equal(quote.tier,'growth');assert.equal(quote.service,'Business Growth Implementation Programme');assert.equal(quote.amount,7500)});
test('Rescue triage ignores browser supplied score',()=>{const t=scoreRescueTriage({type:'debt',amount:10000,income:5000,expenses:3000,days:60,flags:[],triage:{score:100}});assert.notEqual(t.score,100);assert.equal(t.band,'Low')});
test('critical enforcement flags raise Rescue urgency',()=>{const t=scoreRescueTriage({type:'legal',amount:100000,income:10000,expenses:11000,days:2,flags:['summons','repossession']});assert.equal(t.band,'Critical');assert.ok(t.score>=80)});
test('unknown Rescue flags are discarded',()=>{const t=scoreRescueTriage({type:'tax',flags:['tax_debt','invented_flag']});assert.deepEqual(t.flags,['tax_debt'])});
test('negative financial inputs are clamped',()=>{const t=scoreRescueTriage({type:'debt',amount:-5,income:-10,expenses:-20,days:-1});assert.equal(t.amount,0);assert.equal(t.income,0);assert.equal(t.expenses,0);assert.equal(t.days,0)});
console.log('All Chancellor core integrity tests passed.');
