const assert=require('node:assert/strict');
const {hashSecret,verifySecret,pfEncode,payfastSignature,scoreAudit}=require('../core');
const {scoreReadiness,publicDefinition}=require('../readiness-engine');
const {scoreRescueTriage}=require('../rescue-triage');

function test(name,fn){try{fn();console.log(`✓ ${name}`)}catch(error){console.error(`✗ ${name}`);throw error}}

test('access secrets verify and reject wrong values',()=>{const stored=hashSecret('ABCD1234');assert.equal(verifySecret('ABCD1234',stored),true);assert.equal(verifySecret('WRONG',stored),false)});
test('PayFast signatures are deterministic and sensitive to amount',()=>{const a=payfastSignature({merchant_id:'10000100',amount:'199.00',item_name:'Membership'},'secret');const b=payfastSignature({merchant_id:'10000100',amount:'199.00',item_name:'Membership'},'secret');const c=payfastSignature({merchant_id:'10000100',amount:'999.00',item_name:'Membership'},'secret');assert.equal(a,b);assert.notEqual(a,c)});
test('PayFast signature encoding matches PHP-style form encoding for special characters',()=>{assert.equal(pfEncode("O'Reilly! * Test~(1)"),'O%27Reilly%21+%2A+Test%7E%281%29');const signature=payfastSignature({merchant_id:'10000100',amount:'199.00',item_name:"O'Reilly! * Test~(1)"},'S!gn~Key*(A)');assert.equal(signature,'1eaf59a8c1b554676edc20d51af8c5a9')});
test('legacy business readiness score caps at 90',()=>{const yes={};for(let i=1;i<=45;i++)yes[`q${String(i).padStart(2,'0')}`]='2';const result=scoreAudit(yes);assert.equal(result.score,90);assert.equal(result.maxScore,90);assert.equal(result.band,'GREEN - Growth ready');assert.equal(result.readinessPercent,100)});
test('legacy business readiness supports partial scoring and priority sections',()=>{const answers={};for(let i=1;i<=45;i++)answers[`q${String(i).padStart(2,'0')}`]='1';for(let i=1;i<=5;i++)answers[`q${String(i).padStart(2,'0')}`]='0';const result=scoreAudit(answers);assert.equal(result.sectionScores['Business Foundation'],0);assert.equal(result.sectionScores['Finance & Cash Flow'],5);assert.equal(result.priorities[0].section,'Business Foundation');assert.equal(result.band,'AMBER - Needs strengthening')});
test('browser supplied legacy readiness totals are ignored',()=>{const result=scoreAudit({score:90,band:'GREEN - Growth ready',q01:'2'});assert.equal(result.score,2);assert.notEqual(result.band,'GREEN - Growth ready')});
test('225-point readiness definition contains 9 sections and 45 questions',()=>{const definition=publicDefinition();assert.equal(definition.length,9);assert.equal(definition.flatMap(s=>s.questions).length,45);assert.equal(definition.reduce((sum,s)=>sum+s.weight,0),225)});
test('225-point readiness engine reaches exactly 225 for fully ready business',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='5';const result=scoreReadiness({answers});assert.equal(result.score,225);assert.equal(result.maxScore,225);assert.equal(result.readinessPercent,100);assert.equal(result.bandCode,'STRONG_FOUNDATION');assert.equal(result.recommendations.length,1)});
test('225-point readiness engine finds three weakest priorities',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='5';for(const question of publicDefinition()[1].questions)answers[question.id]='1';const result=scoreReadiness({answers,score:225});assert.equal(result.priorities[0].section,'Financial Readiness');assert.ok(result.score<225);assert.equal(result.priorities.length,3)});
test('multiple weak areas trigger Growth Accelerator',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='5';for(const section of publicDefinition().slice(0,4))for(const question of section.questions)answers[question.id]='1';const result=scoreReadiness({answers});assert.ok(result.weakSectionCount>=4);assert.equal(result.priorityIntervention,'Growth Accelerator')});
test('funding goal prioritises Funding Readiness when weak',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='5';const funding=publicDefinition().find(s=>s.key==='funding');for(const question of funding.questions)answers[question.id]='1';const result=scoreReadiness({answers,goal:'Obtain funding'});assert.equal(result.priorityIntervention,'Funding Readiness Package')});
test('tender goal prioritises Tender Readiness when weak',()=>{const answers={};for(const section of publicDefinition())for(const question of section.questions)answers[question.id]='5';const tender=publicDefinition().find(s=>s.key==='tender');for(const question of tender.questions)answers[question.id]='1';const result=scoreReadiness({answers,goal:'Win tenders'});assert.equal(result.priorityIntervention,'Tender Readiness Package')});
test('Rescue triage ignores browser supplied score',()=>{const t=scoreRescueTriage({type:'debt',amount:10000,income:5000,expenses:3000,days:60,flags:[],triage:{score:100}});assert.notEqual(t.score,100);assert.equal(t.band,'Low')});
test('critical enforcement flags raise Rescue urgency',()=>{const t=scoreRescueTriage({type:'legal',amount:100000,income:10000,expenses:11000,days:2,flags:['summons','repossession']});assert.equal(t.band,'Critical');assert.ok(t.score>=80)});
test('unknown Rescue flags are discarded',()=>{const t=scoreRescueTriage({type:'tax',flags:['tax_debt','invented_flag']});assert.deepEqual(t.flags,['tax_debt'])});
test('negative financial inputs are clamped',()=>{const t=scoreRescueTriage({type:'debt',amount:-5,income:-10,expenses:-20,days:-1});assert.equal(t.amount,0);assert.equal(t.income,0);assert.equal(t.expenses,0);assert.equal(t.days,0)});
console.log('All Chancellor core integrity tests passed.');
